1. **Blocking — verification paths are rooted incorrectly.** `Verification.run_target/5` stores logs relative to `env.root` (`lib/kogen/build/verification.ex:253-305`); proof and base-suite receipts do the same (`lib/kogen/build/proof_selectors.ex:279-304`, `lib/kogen/build/ledger.ex:202-221`), while settlement resolves them from control (`lib/kogen/build/verification.ex:635-657`). Ledger diff paths likewise use the Candidate root (`lib/kogen/build/ledger.ex:63-81`). This contradicts [INTENT.md:173-182](.kogen/intents/drafts/isolated-candidate-workspace/INTENT.md:173). **Minimal package fix:** specify separate `candidate_root`/`control_root` parameters and require every receipt, proof, base-suite and ledger locator to be control-relative, with settlement verified from a third cwd.

2. **Blocking — TargetEvidence cannot be revalidated from the Candidate.** Capture receives the Candidate root, but later validation omits it (`lib/kogen/build/verification.ex:602-606`; `lib/kogen/build.ex:1387-1411`). The immutable verification context stores only `project_root` (control) (`lib/kogen/build/verification.ex:47-58`). **Minimal package fix:** require `candidate_root` in the persisted verification context and require `settle/3`, state validation and publication checks to pass it to every `TargetEvidence.verify/2`.

3. **Blocking — the KOGEN_WRITE_BOUNDARY claim is false at the landed code.** `VerificationRunner.@scrubbed` omits `KOGEN_WRITE_BOUNDARY` (`lib/kogen/build/verification_runner.ex:17`), and the runner does not inject the promised default `KOGEN_LIVE_LOG_DIR` (`lib/kogen/build/verification_runner.ex:114-120`). Thus controller verification can inherit a role boundary, and live evidence can remain in the removable Candidate. This contradicts [INTENT.md:397-404](.kogen/intents/drafts/isolated-candidate-workspace/INTENT.md:397) and [scenarios.yaml:222-248](.kogen/intents/drafts/isolated-candidate-workspace/scenarios.yaml:222). **Minimal package fix:** make the exact scrub-list entry and default live-log injection explicit acceptance conditions, rather than describing them as already added.

4. **Blocking — Mix environment can redirect Candidate verification into control.** The runner inherits `MIX_BUILD_PATH`, `MIX_EXS` and related variables; its scrub list has none (`lib/kogen/build/verification_runner.ex:17,114-120`). Existing fixture code explicitly scrubs these because inherited values leak into nested Mix commands (`test/support/integrity_fixture.ex:100-114`); the intended isolated environment already removes `MIX_EXS`/`MIX_DEPS_PATH` (`lib/kogen/build/base_workspace.ex:79-85`). **Minimal package fix:** require runner children to scrub project/build redirection variables and prove `make -C <Candidate>` compiles and runs from Candidate-owned paths.

5. **Blocking — the third-cwd scenario has no executable control-root contract.** `mix kogen.build` and `Kogen.Build.run/2` accept no control-root argument and use relative paths (`lib/mix/tasks/kogen.build.ex:17-40`, `lib/kogen/build.ex:73-95,230-234`). `candidate_id/0` has no root parameter (`lib/kogen/git.ex:129-159`), `candidate_changes/1` runs `git` without `cd` (`lib/kogen/build.ex:807-829`), and `Verification.project_root/1` silently falls back to `File.cwd!()` (`lib/kogen/build/verification.ex:689-696`). This conflicts with the “third directory” and “no `File.cwd!()` fallback” requirements ([scenarios.yaml:141-188](.kogen/intents/drafts/isolated-candidate-workspace/scenarios.yaml:141)). **Minimal package fix:** define how the control root is captured before cwd changes, thread it through Build/Git/Tracking/ReviewPacket, and require malformed or absent roots to fail closed.

6. **Blocking — the controller report and citation snapshots still inspect control.** `Report.build/1` defaults `existing?` to `File.regular?/1` on the process cwd (`lib/kogen/build/report.ex:29-34`), and `snapshot_references/2` relativizes paths against `File.cwd!()` (`lib/kogen/build.ex:1334-1345`). Candidate-only selectors or artifacts therefore appear missing or are read from control, contrary to [scenarios.yaml:148-165](.kogen/intents/drafts/isolated-candidate-workspace/scenarios.yaml:148). **Minimal package fix:** require a Candidate-root predicate for report construction and separate Candidate citation resolution from control tracking-record resolution.

7. **Blocking — role-facing locators are still relative and unusable from Candidate cwd.** The failure prompt relativizes receipts to `File.cwd!()` (`lib/kogen/build.ex:531-550`); reviewer notes print the packet’s relative binding (`lib/kogen/build.ex:1319-1330`); packet and sidecar bindings are also cwd-relative (`lib/kogen/build/review_packet.ex:84-99`, `lib/kogen/build/tracking.ex:104-117,211`). This contradicts [INTENT.md:191-198](.kogen/intents/drafts/isolated-candidate-workspace/INTENT.md:191). **Minimal package fix:** distinguish absolute role-facing paths from control-relative recorded bindings, including packet-internal receipt, ledger-diff and sidecar locators.

8. **Blocking — the hybrid Expert cannot receive the promised Build binding.** `Kogen.Harness.expert_environment/2` sends only route, harness, model, effort and helpers (`lib/kogen/harness.ex:88-109`); `mix kogen.expert` opens from its project argument and re-resolves scope (`lib/mix/tasks/kogen.expert.ex:109-136`, `lib/kogen/codex.ex:47-63`). The external Mix task is not covered by the controller’s preloaded modules. This conflicts with [INTENT.md:127-133](.kogen/intents/drafts/isolated-candidate-workspace/INTENT.md:127). **Minimal package fix:** require `KOGEN_EXPERT` to carry control root, Candidate launch root, bound scope and per-Build harness home, and require an actual subprocess assertion; state how the task avoids loading mutable Candidate Kogen code.

No remaining operational assumption on `shaping-preflight-audit` was found; its references are explicitly conditional or parked. Named selectors are either present, allowed new files, or catalog rehearsal IDs. Each scenario has at most one justified provider target in addition to `check`. No further findings.