defmodule Kogen.FailureSignatureTest do
  use ExUnit.Case, async: true

  alias Kogen.Build.FailureSignature

  test "the first failed receipt remains primary and repeated signatures are explicit" do
    cycle = %{
      "candidate_id" => "candidate-a",
      "sequence" => 2,
      "receipts" => [
        %{
          "target" => "check",
          "status" => "failed",
          "exit_code" => 3,
          "output" => "test/a_test.exs:9 initiating"
        },
        %{
          "target" => "cleanup",
          "status" => "failed",
          "exit_code" => 4,
          "output" => "later cleanup"
        }
      ]
    }

    context = %{"targets" => ["check", "live-native"]}

    catalog = %{
      targets: %{
        "check" => %{"cost_class" => "offline"},
        "live-native" => %{"provider_backed" => true}
      }
    }

    first = FailureSignature.derive(cycle, context, catalog)
    repeated = FailureSignature.derive(cycle, context, catalog, [first])

    assert first["target"] == "check"
    assert first["first_failure"] == "test/a_test.exs:9"
    assert first["before_first_paid"]
    assert first["source"] == "tail"
    refute first["repeated"]
    assert repeated["repeated"]
  end

  test "reproduce is copied into a signature without changing its digest" do
    base_output =
      "KOGEN_FAILURE_SIGNATURE\t" <>
        Jason.encode!(%{
          "stage" => "test",
          "test_id" => "test/example_test.exs:7",
          "assertion" => "assert value == expected"
        })

    with_reproduce =
      "KOGEN_FAILURE_SIGNATURE\t" <>
        Jason.encode!(%{
          "stage" => "test",
          "test_id" => "test/example_test.exs:7",
          "assertion" => "assert value == expected",
          "reproduce" => "MIX_ENV=test mix test --exclude live --warnings-as-errors"
        })

    cycle = fn output ->
      %{
        "candidate_id" => "candidate-a",
        "sequence" => 1,
        "receipts" => [
          %{"target" => "check", "status" => "failed", "exit_code" => 1, "output" => output}
        ]
      }
    end

    without = FailureSignature.derive(cycle.(base_output), %{"targets" => []}, %{targets: %{}})

    with_value =
      FailureSignature.derive(cycle.(with_reproduce), %{"targets" => []}, %{targets: %{}})

    assert with_value["reproduce"] == "MIX_ENV=test mix test --exclude live --warnings-as-errors"
    assert with_value["digest"] == without["digest"]
  end

  describe "against real mined excerpts (evidence/probe-signals, signatures-identify-failures)" do
    @fixtures_dir Path.expand("../support/mined_failures", __DIR__)
    @catalog %{targets: %{}}
    @context %{"targets" => []}

    defp fixture(name) do
      path = Path.join(@fixtures_dir, name)
      json = path |> File.read!() |> Jason.decode!()
      provenance = Map.fetch!(json, "provenance")

      # Every committed excerpt carries its Build id (or, for the one
      # generated fixture, an explicit `generated: true` marker), cycle,
      # source record path and original receipt sha256 as provenance
      # (mined-fixture-ownership).
      if json["generated"] do
        assert provenance["build_id"] == nil
      else
        assert is_binary(provenance["build_id"]) and provenance["build_id"] != ""
        assert is_integer(provenance["cycle"])
      end

      assert is_binary(provenance["source_record_path"]) and
               provenance["source_record_path"] != ""

      assert provenance["sha256"] =~ ~r/^[0-9a-f]{64}$/

      json
    end

    defp derive(output, target \\ "check") do
      cycle = %{
        "candidate_id" => "c",
        "sequence" => 1,
        "receipts" => [
          %{"target" => target, "status" => "failed", "exit_code" => 1, "output" => output}
        ]
      }

      FailureSignature.derive(cycle, @context, @catalog)
    end

    # Frame lines generated by replaying the raw excerpts through offline.py's
    # `--signature-frame` CLI (scenario evidence: "the check excerpts
    # replayed through offline.py's new frame emitter"), then appended, just
    # as offline.py itself would have printed after this repository's own
    # failing `check` stage.
    defp with_frame(output, stage) do
      root = Path.expand("../..", __DIR__)
      tmp = Path.join(System.tmp_dir!(), "kogen-sig-frame-#{System.unique_integer([:positive])}")
      File.write!(tmp, output)

      {frame, 0} =
        System.cmd(
          "sh",
          [
            "-c",
            "python3 -B scripts/check/offline.py --signature-frame #{stage} < #{tmp}"
          ],
          cd: root
        )

      File.rm(tmp)
      output <> "\n" <> frame
    end

    test "check excerpts split by cause although they share today's collapsed digest, via the frame" do
      zj1 = with_frame(fixture("zjdgu9wo_c1_check.json")["output"], "test")
      qp1 = with_frame(fixture("_8qpvuip_c1_check.json")["output"], "test")
      a1 = with_frame(fixture("a2spfuvf_c1_check.json")["output"], "test")

      s_zj1 = derive(zj1)
      s_qp1 = derive(qp1)
      s_a1 = derive(a1)

      assert s_zj1["source"] == "frame"
      assert s_zj1["first_failure"] == "test/kogen/scenario_lifecycle_test.exs:200"
      assert s_qp1["first_failure"] == "test/kogen/commit_provenance_test.exs:24"
      assert s_a1["first_failure"] == "test/kogen/test_reliability_catalog_test.exs:15"

      digests = [s_zj1["digest"], s_qp1["digest"], s_a1["digest"]]
      assert Enum.uniq(digests) == digests
    end

    test "_8Qpvuip cycles 2 and 3 fail the same test (LifecycleTest:21), so cycle 3 is repeated" do
      c2 = with_frame(fixture("_8qpvuip_c2_check.json")["output"], "test")
      c3 = with_frame(fixture("_8qpvuip_c3_check.json")["output"], "test")

      s2 = derive(c2)

      s3_first =
        FailureSignature.derive(
          %{
            "candidate_id" => "c",
            "sequence" => 3,
            "receipts" => [
              %{"target" => "check", "status" => "failed", "exit_code" => 1, "output" => c3}
            ]
          },
          @context,
          @catalog,
          [s2]
        )

      assert s2["first_failure"] == "test/kogen/lifecycle_test.exs:21"
      assert s3_first["first_failure"] == "test/kogen/lifecycle_test.exs:21"
      assert s2["digest"] == s3_first["digest"]
      assert s3_first["repeated"]
    end

    test "a genuine cross-build recurrence (ZJDgU9wo cycle 3, _8Qpvuip cycle 1, CommitProvenanceTest:24) shares a signature" do
      zj3 = with_frame(fixture("zjdgu9wo_c3_check.json")["output"], "test")
      qp1 = with_frame(fixture("_8qpvuip_c1_check.json")["output"], "test")

      assert derive(zj3)["digest"] == derive(qp1)["digest"]
    end

    test "a2sPFUvF cycle 2's assertion sits deep in a long receipt (232 of 262 non-blank lines from the end); the frame still finds it" do
      raw = fixture("a2spfuvf_c2_check.json")["output"]
      output = with_frame(raw, "test")

      lines = raw |> String.split("\n") |> Enum.filter(&(String.trim(&1) != ""))
      assert length(lines) > 200

      signature = derive(output)
      assert signature["source"] == "frame"
      assert signature["first_failure"] == "test/kogen/intent_test.exs:102"

      excerpt = FailureSignature.primary_lines(output)
      assert excerpt =~ "test/kogen/intent_test.exs:102"
    end

    test "hAOGGjSC cycle 1 (PTY EBADF) is distinct from cycle 2 (ExUnit 120000ms timeout)" do
      c1 = with_frame(fixture("haoggjsc_c1_check.json")["output"], "test")
      c2 = with_frame(fixture("haoggjsc_c2_check.json")["output"], "test")

      s1 = derive(c1)
      s2 = derive(c2)

      assert s1["first_failure"] == "test/kogen/harness_role_test.exs:6"
      assert s2["first_failure"] == "test/kogen/offline_stage_results_test.exs:70"
      refute s1["digest"] == s2["digest"]
    end

    test "btwokrNx cycle 3 equals cycle 1 through the fallback (repeated), cycle 2 stays distinct" do
      c1 = fixture("btwokrnx_c1_live_native.json")["output"]
      c2 = fixture("btwokrnx_c2_live_native.json")["output"]
      c3 = fixture("btwokrnx_c3_live_native.json")["output"]

      # No KOGEN_FAILURE_SIGNATURE frame in live-native output: these fall
      # back to the normalized failure tail.
      refute c1 =~ "KOGEN_FAILURE_SIGNATURE"
      assert c1 =~ "launch_reviewer"
      assert c2 =~ "launch_developer"
      assert c3 =~ "launch_reviewer"

      s1 = derive(c1, "live-native")
      s2 = derive(c2, "live-native")

      s3 =
        FailureSignature.derive(
          %{
            "candidate_id" => "c",
            "sequence" => 3,
            "receipts" => [
              %{"target" => "live-native", "status" => "failed", "exit_code" => 1, "output" => c3}
            ]
          },
          @context,
          @catalog,
          [s1]
        )

      assert s1["source"] == "tail"
      assert s1["digest"] == s3["digest"]
      assert s3["repeated"]
      refute s2["digest"] == s1["digest"]
    end

    test "a plain, non-Elixir `make test` output (generated, no frame, no ExUnit header) still gets a discriminating signature" do
      generated = fixture("generated_plain_make_test.json")
      output = generated["output"]
      refute output =~ "KOGEN_FAILURE_SIGNATURE"
      refute output =~ ~r/^\s*\d+\)\s+test /m

      signature = derive(output, "test")
      assert signature["source"] == "tail"
      assert signature["digest"] != nil

      other = derive("running plain_test_suite\ncase_one ... ok\nall green\n", "test")
      refute other["digest"] == signature["digest"]
    end

    test "the fallback digest is never over the offline-gate preamble boilerplate alone" do
      preamble =
        "/usr/bin/time -p python3 scripts/check/offline.py\nResolved Git executable: /usr/bin/git\n"

      output_a = preamble <> "\n\n  1) test alpha (Mod.A)\n     test/a.exs:1\n     boom A\n"
      output_b = preamble <> "\n\n  1) test beta (Mod.B)\n     test/b.exs:1\n     boom B\n"

      refute derive(output_a)["digest"] == derive(output_b)["digest"]
    end

    test "fixture directories named with an epoch, pid or port normalize away; the cause still discriminates" do
      failure = fn run_dir, port, seed, reason ->
        "Randomized with seed #{seed}\n" <>
          "fixture: /Users/dev/kogen/.kogen/runtime/#{run_dir}/stateful-flawed\n" <>
          "connecting to localhost:#{port}\n" <>
          "stateful-flawed failed: #{reason}\n"
      end

      a = derive(failure.("shaping-evaluation-1790357780712-586", 4001, 1, "missing answer"))
      b = derive(failure.("shaping-evaluation-1790363015551-9124", 52_311, 2, "missing answer"))
      c = derive(failure.("shaping-evaluation-1790363015551-9124", 52_311, 2, "draft invalid"))

      assert a["digest"] == b["digest"]
      refute c["digest"] == b["digest"]
    end
  end

  describe "primary_lines/2 (handoff-lists-all-evidence)" do
    test "prefers the frame's fields when present" do
      output =
        "noise\n" <>
          "KOGEN_FAILURE_SIGNATURE\t" <>
          Jason.encode!(%{"stage" => "test", "test_id" => "test/x.exs:1", "assertion" => "boom"})

      excerpt = FailureSignature.primary_lines(output)
      assert excerpt =~ "test/x.exs:1"
      assert excerpt =~ "boom"
    end

    test "without a frame, the excerpt starts at the failure block and runs to the output's tail" do
      preamble = String.duplicate("noise line\n", 300)

      output =
        preamble <>
          "\n  1) test something (Mod)\n     test/x.exs:9\n     Assertion with == failed\n" <>
          "\nFinished in 0.1 seconds\nResult: 0/1 passed\n"

      excerpt = FailureSignature.primary_lines(output, 500)
      assert excerpt =~ "test/x.exs:9"
      assert excerpt =~ "Assertion with == failed"
      refute excerpt =~ "noise line"
    end

    test "stays within its bound even for a very long failure block" do
      block =
        "\n  1) test something (Mod)\n     test/x.exs:9\n     the real reason\n" <>
          String.duplicate("filler\n", 5_000) <> "\nResult: the tail marker\n"

      excerpt = FailureSignature.primary_lines(block, 800)
      assert String.length(excerpt) <= 800
      assert excerpt =~ "the real reason"
      assert excerpt =~ "the tail marker"
    end
  end

  describe "primary_lines/2 keeps a make target's own failing output" do
    test "a target echoing a marker-free message then exiting 1 keeps that line" do
      dir =
        Path.join(
          System.tmp_dir!(),
          "kogen-failure-signature-#{Base.url_encode64(:crypto.strong_rand_bytes(12), padding: false)}"
        )

      File.mkdir!(dir)
      on_exit(fn -> File.rm_rf!(dir) end)

      File.write!(
        Path.join(dir, "Makefile"),
        "check:\n\t@echo 'dummy.txt is missing. Required exact content: shape2build-k4q9z'\n\t@exit 1\n"
      )

      {output, 2} =
        System.cmd("make", ["check"],
          cd: dir,
          stderr_to_stdout: true,
          env: [{"MAKELEVEL", nil}, {"MAKEFLAGS", nil}, {"MFLAGS", nil}]
        )

      assert output =~ "Error 1"

      excerpt = FailureSignature.primary_lines(output)
      assert excerpt =~ "Required exact content: shape2build-k4q9z"
      assert excerpt =~ ~r/make(\[\d+\])?: \*\*\* \[(?:[^\]]*: )?check\] Error 1/
    end

    test "long unrelated output before the message does not crowd it out" do
      output =
        String.duplicate("compiling noise\n", 100) <>
          "dummy.txt is missing. Required exact content: abc123\nmake: *** [check] Error 1\n"

      excerpt = FailureSignature.primary_lines(output, 400)
      assert excerpt =~ "Required exact content: abc123"
      assert excerpt =~ "make: *** [check] Error 1"
    end

    test "the lead-in also works for a nested make[1] marker" do
      output =
        String.duplicate("compiling noise\n", 100) <>
          "dummy.txt is missing. Required exact content: abc123\nmake[1]: *** [check] Error 1\n"

      excerpt = FailureSignature.primary_lines(output, 400)
      assert excerpt =~ "Required exact content: abc123"
      assert excerpt =~ "make[1]: *** [check] Error 1"
    end
  end
end
