#!/usr/bin/env bash
# restart_server.sh — stop running server processes (local dev).
#
# Generated by codegen-scaffold (no platform RPC configured).

set -euo pipefail

printf '[restart_server] stopping server processes (best-effort)...\n'
pkill -f 'phx.server\|mix phx\|npm run serve' 2>/dev/null || true
printf '[restart_server] done — start your server manually\n'
