/**
 * no-interactive-beam.ts — Pi enforcement: deny a bare `erl -eval`/`-run`
 * invocation missing `-noshell` and bare interactive `iex` (no -e/--eval).
 *
 * Mirrors: harnesses/claude/hooks/no-interactive-beam.sh
 * Event: tool_call
 * Matcher: bash
 *
 * GENERATED FROM shared/enforcement/registry.yaml — header/metadata only.
 * Hand-authored body (AND-NOT logic — "erl -eval AND NOT -noshell" — is
 * beyond the compiler's match/match_all AND-only templates, same reason
 * no-silent-failure.ts is hand-authored). NOT regenerated by the compiler;
 * edit this file directly to change matching behavior.
 *
 * Denies:
 *   1. `erl` with `-eval` or `-run` when `-noshell` is absent anywhere in the
 *      command — the F6 hang: evaluates the expression then drops into the
 *      interactive Erlang shell, which blocks on absent stdin until the
 *      build-context command timeout kills it.
 *   2. bare interactive `iex` (no `-e`/`--eval`) — future-proofing; no
 *      current legit in-repo use, but the same interactive-drop hang
 *      applies.
 *
 * Allows (no false positive):
 *   - `erl -noshell -eval '...' -s init stop` / `... halt().`
 *   - `elixir -e '...'` (evaluates and exits; shell-safe)
 *   - `iex -e '...'` / `iex --eval '...'` (non-interactive eval-and-run)
 *   - gate commands (`make test`, `mix compile`, etc.)
 *
 * Residual (by design, not a bug): a self-SIGINT to a non-interactive BEAM
 * living inside Elixir source (inline `elixir -e '...os.cmd...'` or a
 * `.exs` file) is command-invisible to this hook — no command-string
 * matcher can inspect Elixir source semantics. That class is addressed by
 * the BEAM-probe-discipline rule in shared/rules/stacks/phoenix/_core.md,
 * not this hook.
 */

import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { deny, debugLog, isCodegenLogWrite, stripQuoted } from "../lib/hook-helpers";

export const HANDLER_META = {
  name: "no-interactive-beam",
  event: "tool_call",
  matcher: "bash",
} as const;

const DENY_MESSAGE =
  "BLOCKED by no-interactive-beam: bare 'erl -eval'/'-run' and interactive 'iex' drop to a shell that blocks on absent stdin in the non-interactive build context. Use 'erl -noshell -eval '...' -s init stop' (or 'halt().'), or 'elixir -e '...'' (shell-safe). Never self-signal INT/SIGINT to a non-interactive BEAM.";

const ERL_EVAL_RUN_RE = /\berl\b[^;&|]*(-eval|-run)\b/;
const ERL_NOSHELL_RE = /\berl\b[^;&|]*-noshell\b/;
const BARE_IEX_RE = /(^|[;&|]|\s)iex\b/;
const IEX_EVAL_RE = /\biex\b[^;&|]*(-e|--eval)\b/;

export function register(pi: ExtensionAPI): void {
  pi.on("tool_call", async (event) => {
    if (event.toolName !== "bash") return;

    const _role = process.env["CLAUDE_ROLE"] || process.env["PI_ROLE"] || "";
    if (["debug", "shape", "ops"].includes(_role)) return;

    const command: string = (event.input as { command?: string }).command ?? "";
    debugLog("no-interactive-beam", `cmd=${command}`);

    // A codegen-log write narrates gated phrases in its heredoc body; it is
    // never the gated action itself. Bypass before any phrase match.
    if (isCodegenLogWrite(command)) return;

    const stripped = stripQuoted(command);

    if (ERL_EVAL_RUN_RE.test(stripped) && !ERL_NOSHELL_RE.test(stripped)) {
      return deny(DENY_MESSAGE);
    }

    if (BARE_IEX_RE.test(stripped) && !IEX_EVAL_RE.test(stripped)) {
      return deny(DENY_MESSAGE);
    }
  });
}
