/**
 * no-silent-failure.ts — Pi enforcement: deny high-precision silent-failure
 * swallow tokens in write/edit content unless a justified
 * `# fail-loud-exempt: <reason>` comment is present.
 *
 * Mirrors: harnesses/claude/hooks/no-silent-failure.sh
 * Event: tool_call
 * Matcher: write|edit|multiedit
 *
 * GENERATED FROM shared/enforcement/registry.yaml — header/metadata only.
 * Hand-authored body (compiler COMMAND/FILE_PATH sources cannot inspect
 * write/edit content — see context/enforcement-compiler.md). Mirrors the
 * hand-authored precedent of context-curator-guard.ts. NOT regenerated by
 * the compiler; edit this file directly to change matching behavior.
 *
 * Matches four token classes:
 *   1. empty catch {}                              (TS)
 *   2. bare except: / except Exception:             (Python)
 *   3. rescue _ -> / rescue <var> -> w/o reraise    (Elixir)
 *   4. catch-all _ -> nil|:ok|[]|""  sink           (Elixir)
 *
 * Bypassed by:
 *   - a `# fail-loud-exempt: <reason>` comment anywhere in the new content
 *     (reason after the colon is MANDATORY — a bare token still denies)
 *   - `reraise` appearing anywhere in the new content (covers the rescue
 *     class's narrow legit shape; prefer false-ALLOW over false-DENY)
 *
 * Deliberately NOT gated (reviewer-owned, contextual — see Rule S in
 * shared/rules/roles/reviewer.md): `|| true`, `2>/dev/null || true`,
 * Keyword.get/Map.get/System.get_env default-value calls.
 *
 * Fidelity note: all four token classes are dialect-neutral regex (no
 * backreferences/lookaround) and are expressed identically to the bash
 * twin — no reduced-fidelity gap for this hook.
 */

import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { deny, debugLog } from "../lib/hook-helpers";

export const HANDLER_META = {
  name: "no-silent-failure",
  event: "tool_call",
  matcher: "write|edit|multiedit",
} as const;

const EXEMPT_RE = /#[ \t]*fail-loud-exempt:[ \t]*\S+/;
const RERAISE_RE = /\breraise\b/;
const EMPTY_CATCH_RE = /catch\s*(\([^)]*\))?\s*\{\s*\}/;
const BARE_EXCEPT_RE = /^[ \t]*except(\s+Exception)?\s*:\s*$/m;
const RESCUE_NO_RERAISE_RE = /\brescue\s+(_|[a-zA-Z_][a-zA-Z0-9_]*)\s*->/;
const CATCHALL_SINK_RE = /_\s*->\s*(nil|:ok|\[\]|"")(\s|$)/;

export function register(pi: ExtensionAPI): void {
  pi.on("tool_call", async (event) => {
    if (
      !(
        event.toolName === "write" ||
        event.toolName === "edit" ||
        event.toolName === "multiedit"
      )
    )
      return;

    // A write/edit tool_call has no `command` field (only Bash tool_calls
    // do), so the isCodegenLogWrite command-scan bypass used by Bash-facing
    // hooks does not apply here. codegen-log itself is a Bash invocation —
    // it never appears as a write/edit tool_call — so no bypass is needed.
    const input = event.input as {
      content?: string;
      new_string?: string;
      edits?: Array<{ new_string?: string }>;
    };

    const newContent: string =
      input.content ??
      input.new_string ??
      (input.edits ?? []).map((e) => e.new_string ?? "").join("\n") ??
      "";

    debugLog("no-silent-failure", `tool=${event.toolName} len=${newContent.length}`);

    if (!newContent) return;

    if (EXEMPT_RE.test(newContent)) return;

    const hasReraise = RERAISE_RE.test(newContent);

    if (EMPTY_CATCH_RE.test(newContent)) {
      return deny(
        "BLOCKED by no-silent-failure: empty catch {} swallows all errors silently. Handle the error (log + reraise/rethrow) or add '# fail-loud-exempt: <reason>' with a mandatory justification. See fail-loud rule.",
      );
    }

    if (BARE_EXCEPT_RE.test(newContent)) {
      return deny(
        "BLOCKED by no-silent-failure: bare 'except:' / 'except Exception:' swallows all errors including bugs. Catch the specific exception or add '# fail-loud-exempt: <reason>' with a mandatory justification. See fail-loud rule.",
      );
    }

    if (!hasReraise && RESCUE_NO_RERAISE_RE.test(newContent)) {
      return deny(
        "BLOCKED by no-silent-failure: 'rescue _ ->' / 'rescue <var> ->' without reraise swallows the error. Use 'reraise e, __STACKTRACE__' to preserve it, or add '# fail-loud-exempt: <reason>' with a mandatory justification. See fail-loud rule.",
      );
    }

    if (CATCHALL_SINK_RE.test(newContent)) {
      return deny(
        'BLOCKED by no-silent-failure: catch-all \'_ -> nil|:ok|[]|""\' sink silently discards an unexpected condition. Enumerate the expected cases or raise on the unmatched arm, or add \'# fail-loud-exempt: <reason>\' with a mandatory justification. See fail-loud rule.',
      );
    }
  });
}
