#!/bin/bash
# no-interactive-beam.sh — PreToolUse hook: deny a bare `erl -eval`/`-run`
# invocation missing `-noshell` and bare interactive `iex` (no -e/--eval).
#
# HOOK-MANIFEST:
# event: PreToolUse
# matcher: Bash
# surface: user_global
# signal: none
# role: *
# harnesses: all
# rationale: Denies a bare 'erl -eval'/'-run' invocation missing -noshell (drops into an interactive shell that blocks on absent stdin until the Bash tool's 600s ceiling) and bare interactive 'iex' (no -e/--eval). Allows the safe '-noshell ... -s init stop'/'halt().' form and 'elixir -e' (evaluates and exits). AND-NOT logic (match minus -noshell) is beyond the compiler's match/match_all AND-only templates, so this is hand-authored (kind: registration) like no-silent-failure. Does NOT catch a self-SIGINT to a non-interactive BEAM buried inside Elixir source (inline -e body or .exs file) — that class is command-invisible and addressed by the BEAM-probe-discipline rule in shared/rules/stacks/phoenix/_core.md, not this hook.
# registration only (hand-authored body) — the registry entry for this hook
# is `kind: registration`, which emits ONLY the settings.json wiring; the
# check logic below is NOT generated and is safe to hand-edit.
#
# Hand-authored body (compiler match/match_all templates are AND-only and
# cannot express "erl -eval AND NOT -noshell" — see
# context/enforcement-compiler.md). Registry carries the header only
# (kind: registration); this body is byte-stable and is NOT regenerated by
# the compiler.
#
# Denies:
#   1. `erl` with `-eval` or `-run` when `-noshell` is absent anywhere in the
#      command — the F6 hang: evaluates the expression then drops into the
#      interactive Erlang shell, which blocks on absent stdin until the Bash
#      tool's 600s ceiling kills it.
#   2. bare interactive `iex` (no `-e`/`--eval`) — future-proofing; no current
#      legit in-repo use, but the same interactive-drop hang applies.
#
# Allows (no false positive):
#   - `erl -noshell -eval '...' -s init stop` / `... halt().` (used today in
#     record-green.sh, templates/.vscode/ai-agent.sh)
#   - `elixir -e '...'` (evaluates and exits; shell-safe)
#   - `iex -e '...'` / `iex --eval '...'` (non-interactive eval-and-run)
#   - gate commands (`make test`, `mix compile`, etc.)
#
# Residual (by design, not a bug): a self-SIGINT to a non-interactive BEAM
# living inside Elixir source (inline `elixir -e '...os.cmd...'` or a
# `.exs` file) is command-invisible to this hook — no command-string
# matcher can inspect Elixir source semantics. That class is addressed by
# the BEAM-probe-discipline rule, not this hook.

set -u

source "$(dirname "$0")/lib/hooks-lib.sh"
source "$(dirname "$0")/_role.sh"
parse_input

debug_log no-interactive-beam "tool=$TOOL_NAME agent=$AGENT_TYPE cmd=$COMMAND"

# Only guard Bash tool.
if [ "$TOOL_NAME" != "Bash" ]; then
    exit 0
fi

_role=$(resolve_role)
for _m in debug shape ops; do [ "$_role" = "$_m" ] && exit 0; done

# A codegen-log write narrates gated phrases in its heredoc body; it is never
# the gated action itself. Bypass before any phrase match or counter increment.
if is_codegen_log_write; then
    exit 0
fi

_stripped=$(strip_quoted "$COMMAND")

# Deny 1: bare `erl` with `-eval`/`-run` missing `-noshell` anywhere in the
# command. AND-NOT: match erl+eval/run, then require -noshell absence.
if printf '%s' "$_stripped" | grep -qE '\berl\b[^;&|]*(-eval|-run)\b'; then
    if ! printf '%s' "$_stripped" | grep -qE '\berl\b[^;&|]*-noshell\b'; then
        deny "BLOCKED by no-interactive-beam: bare 'erl -eval'/'-run' and interactive 'iex' drop to a shell that blocks on absent stdin in the non-interactive build context. Use 'erl -noshell -eval '...' -s init stop' (or 'halt().'), or 'elixir -e '...'' (shell-safe). Never self-signal INT/SIGINT to a non-interactive BEAM."
        exit 0
    fi
fi

# Deny 2: bare interactive `iex` (no -e/--eval anywhere in the command).
if printf '%s' "$_stripped" | grep -qE '(^|[;&|]|[[:space:]])iex\b'; then
    if ! printf '%s' "$_stripped" | grep -qE '\biex\b[^;&|]*(-e|--eval)\b'; then
        deny "BLOCKED by no-interactive-beam: bare 'erl -eval'/'-run' and interactive 'iex' drop to a shell that blocks on absent stdin in the non-interactive build context. Use 'erl -noshell -eval '...' -s init stop' (or 'halt().'), or 'elixir -e '...'' (shell-safe). Never self-signal INT/SIGINT to a non-interactive BEAM."
        exit 0
    fi
fi

exit 0
