#!/bin/bash
# no-silent-failure.sh — PreToolUse hook: deny high-precision silent-failure
# swallow tokens in Edit/Write/MultiEdit content unless a justified
# `# fail-loud-exempt: <reason>` comment is present.
#
# HOOK-MANIFEST:
# event: PreToolUse
# matcher: Edit|Write|MultiEdit
# surface: user_global
# signal: none
# role: *
# harnesses: all
# rationale: Denies an Edit/Write/MultiEdit whose new content/new_string contains a high-precision silent-failure swallow token: empty catch {} (TS), bare except: / except Exception: (Python), rescue _ / rescue <var> without reraise in the arm (Elixir), or a catch-all _ -> (nil|:ok|[]|"") sink. Bypassed by a justified `# fail-loud-exempt: <reason>` comment (reason mandatory) or when `reraise` appears anywhere in the new content. Does NOT gate `|| true` or Keyword.get/Map.get/get_env default-value calls — those are reviewer-owned contextual judgment (Rule S), not mechanically precise enough for a keystroke-level deny. Hand-authored (kind: registration) because the compiler's COMMAND/FILE_PATH source templates cannot inspect Edit/Write content.
# GENERATED FROM shared/enforcement/registry.yaml — DO NOT EDIT
#
# Hand-authored body (compiler COMMAND/FILE_PATH sources cannot match edit
# content — see context/enforcement-compiler.md). Registry carries the
# header only (kind: registration); this body is byte-stable and is NOT
# regenerated by the compiler.
#
# Matches four token classes:
#   1. empty catch {}                              (TS)
#   2. bare except: / except Exception:             (Python)
#   3. rescue _ -> / rescue <var> -> w/o reraise    (Elixir)
#   4. catch-all _ -> nil|:ok|[]|""  sink           (Elixir)
#
# Bypassed by:
#   - a `# fail-loud-exempt: <reason>` comment anywhere in the new content
#     (reason after the colon is MANDATORY — a bare token still denies)
#   - `reraise` appearing anywhere in the new content (covers the rescue
#     class's narrow legit shape; prefer false-ALLOW over false-DENY)
#
# Deliberately NOT gated (reviewer-owned, contextual — see Rule S in
# shared/rules/roles/reviewer.md): `|| true`, `2>/dev/null || true`,
# Keyword.get/Map.get/System.get_env default-value calls.

set -u

source "$(dirname "$0")/lib/hooks-lib.sh"
parse_input

# Only guard content-writing tools.
case "$TOOL_NAME" in
Edit | Write | MultiEdit) ;;
*)
    exit 0
    ;;
esac

# codegen-log narrates gated phrases in its heredoc body — never the gated
# action. Bypass before any content match.
if is_codegen_log_write; then
    exit 0
fi

# Extract the content being written (Write→content, Edit→new_string,
# MultiEdit→concat of edits[].new_string). Mirrors context-curator-guard.sh
# content extraction convention.
new_content=$(printf '%s' "$RAW_INPUT" | jq -r '
  .tool_input.content // .tool_input.new_string //
  ([.tool_input.edits[]?.new_string] | join("\n")) // ""' 2>/dev/null) || exit 0

[ -z "$new_content" ] && exit 0

# Exemption 1: a justified `# fail-loud-exempt: <reason>` (reason mandatory)
# anywhere in the new content bypasses the deny. Bare token (no reason,
# nothing but whitespace after the colon) still denies.
if printf '%s' "$new_content" | grep -qE '#[[:space:]]*fail-loud-exempt:[[:space:]]*[^[:space:]]+'; then
    exit 0
fi

# Exemption 2: `reraise` anywhere in the new content — covers the narrow
# legit rescue-and-reraise shape without needing arm-scoped parsing.
has_reraise=0
if printf '%s' "$new_content" | grep -qE '\breraise\b'; then
    has_reraise=1
fi

# Class 1: empty TS catch {}
if printf '%s' "$new_content" | grep -qE 'catch[[:space:]]*(\([^)]*\))?[[:space:]]*\{[[:space:]]*\}'; then
    deny "BLOCKED by no-silent-failure: empty catch {} swallows all errors silently. Handle the error (log + reraise/rethrow) or add '# fail-loud-exempt: <reason>' with a mandatory justification. See fail-loud rule."
    exit 0
fi

# Class 2: bare Python except: / except Exception:  (line-oriented; the
# `pass` body is not required to fire — a bare/broad except with no
# re-raise is itself the swallow).
if printf '%s' "$new_content" | grep -qE '^[[:space:]]*except([[:space:]]+Exception)?[[:space:]]*:[[:space:]]*$'; then
    deny "BLOCKED by no-silent-failure: bare 'except:' / 'except Exception:' swallows all errors including bugs. Catch the specific exception or add '# fail-loud-exempt: <reason>' with a mandatory justification. See fail-loud rule."
    exit 0
fi

# Class 3: Elixir rescue _ -> / rescue <var> -> without reraise anywhere
# in the new content.
if [ "$has_reraise" -eq 0 ] && printf '%s' "$new_content" | grep -qE '\brescue[[:space:]]+(_|[a-zA-Z_][a-zA-Z0-9_]*)[[:space:]]*->'; then
    deny "BLOCKED by no-silent-failure: 'rescue _ ->' / 'rescue <var> ->' without reraise swallows the error. Use 'reraise e, __STACKTRACE__' to preserve it, or add '# fail-loud-exempt: <reason>' with a mandatory justification. See fail-loud rule."
    exit 0
fi

# Class 4: Elixir catch-all sink _ -> nil|:ok|[]|""
if printf '%s' "$new_content" | grep -qE '_[[:space:]]*->[[:space:]]*(nil|:ok|\[\]|"")([[:space:]]|$)'; then
    deny "BLOCKED by no-silent-failure: catch-all '_ -> nil|:ok|[]|\"\"' sink silently discards an unexpected condition. Enumerate the expected cases or raise on the unmatched arm, or add '# fail-loud-exempt: <reason>' with a mandatory justification. See fail-loud rule."
    exit 0
fi

exit 0
