Code.require_file("test/support/dependency_fixture.ex")
root = Path.join(System.tmp_dir!(), "kogen-shaping-copy-#{System.unique_integer([:positive])}")
File.mkdir!(root)
try do
  source = Path.join(root, "source")
  destination = Path.join(root, "destination")
  external = Path.join(root, "external")
  File.mkdir!(source)
  File.mkdir!(external)
  File.write!(Path.join(source, "fresh"), "source")
  File.write!(Path.join(external, "sentinel"), "external")
  File.ln_s!(Path.join(external, "sentinel"), Path.join(source, "linked"))
  File.mkdir!(destination)
  File.write!(Path.join(destination, "stale"), "preexisting")
  Kogen.DependencyFixture.copy!(source, destination)
  IO.inspect(File.exists?(Path.join(destination, "stale")), label: "existing destination silently merged")
  File.write!(Path.join(destination, "linked"), "changed through fixture")
  IO.inspect(File.read!(Path.join(external, "sentinel")), label: "external source after copied-link mutation")
  linked_destination = Path.join(root, "destination-link")
  File.ln_s!(external, linked_destination)
  Kogen.DependencyFixture.copy!(source, linked_destination)
  IO.inspect(File.exists?(Path.join(external, "fresh")), label: "destination symlink target received copy")
after
  File.rm_rf!(root)
end
