defmodule Kogen.IsolatedCase do
  @moduledoc false

  # Tests which change the VM's cwd or environment cannot safely share the
  # outer ExUnit VM.  The parent test below is deliberately only a dispatcher:
  # the original test source is loaded again in a fresh VM, where this module
  # becomes a normal ExUnit.Case.
  @child_marker "KOGEN_ISOLATED_CASE_CHILD"
  @default_timeout 120_000

  defmacro __using__(options) do
    options = Keyword.put(options, :async, true)

    if System.get_env(@child_marker) == "1" do
      quote do
        use ExUnit.Case, Kogen.IsolatedCase.child_case_options(unquote(options))
      end
    else
      quote do
        use ExUnit.Case, unquote(options)
        import ExUnit.Case, except: [test: 2, test: 3]
        import Kogen.IsolatedCase, only: [test: 2, test: 3]
      end
    end
  end

  defmacro test(message, contents) do
    dispatch_test(message, quote(do: _), contents, __CALLER__)
  end

  defmacro test(message, context, contents) do
    dispatch_test(message, context, contents, __CALLER__)
  end

  defp dispatch_test(message, context, contents, caller) do
    source = Path.expand(caller.file)
    body = Keyword.fetch!(contents, :do)

    quote do
      ExUnit.Case.test unquote(message), isolated_context do
        case isolated_context do
          unquote(context) ->
            # Keep the source body in the parent module's lexical analysis so
            # normal compiler warnings remain meaningful, without ever running
            # cwd/env-mutating code in the parent VM.
            if false do
              unquote(body)
            else
              Kogen.IsolatedCase.run!(unquote(source), isolated_context.test,
                timeout: Map.get(isolated_context, :timeout, unquote(@default_timeout)),
                parameters: isolated_context
              )
            end
        end
      end
    end
  end

  @doc """
  Runs one trusted test from `source` in a new Elixir VM.

  `selector` is either the test source line (the form used by the macro) or an
  ExUnit test name. It intentionally accepts a source file rather than a
  closure: a closure cannot cross VM boundaries safely.
  """
  @spec run(Path.t(), pos_integer() | String.t() | atom(), keyword() | map()) ::
          {:ok, binary()} | {:error, term(), binary()}
  def run(source, selector, options \\ []) do
    options = normalize_options(options)
    source = Path.expand(source)
    root = Path.expand(System.fetch_env!("KOGEN_TEST_ROOT"))
    working_dir = Path.expand(Keyword.get(options, :cd, root))
    timeout = Keyword.get(options, :timeout, @default_timeout)
    tmpdir = private_tmpdir(options)

    # Until Port.open/2 succeeds, no supervisor can clean this root. Keep the
    # setup in a separate ownership phase so failed argument or environment
    # preparation does not retain a private fixture.
    port =
      try do
        args = child_args(root, source, selector)
        env = child_env(options, tmpdir)
        open_supervisor(args, working_dir, env, timeout)
      rescue
        exception ->
          cleanup_unowned_tmpdir(tmpdir)
          reraise exception, __STACKTRACE__
      catch
        kind, reason ->
          cleanup_unowned_tmpdir(tmpdir)
          :erlang.raise(kind, reason, __STACKTRACE__)
      end

    collection_timeout = Keyword.get(options, :collection_timeout, timeout + 2_000)

    {status, output} =
      collect_port(port, [], System.monotonic_time(:millisecond) + collection_timeout)

    # Port.open can return before the OS launcher rejects its cwd. Only after
    # confirmed exit may we reclaim a root whose supervisor never started.
    if File.dir?(tmpdir) and not File.exists?(Path.join(tmpdir, "supervisor-started")) do
      cleanup_unowned_tmpdir(tmpdir)
    end

    # The supervisor alone removes its temporary root, after reaping children.
    # In particular, cancellation must never race parent-side fixture removal.
    case status do
      0 -> {:ok, output}
      124 -> {:error, :timeout, output}
      :timeout -> {:error, :timeout, output}
      status -> {:error, {:exit_status, status}, output}
    end
  end

  @doc false
  def child_case_options(options) do
    case if(Keyword.has_key?(options, :parameterize),
           do: System.get_env("KOGEN_ISOLATED_PARAMETERS")
         ) do
      nil ->
        options

      encoded ->
        # This value is generated by the parent dispatcher immediately before
        # spawning this trusted child; `:safe` would reject the test module atom
        # because the source has not been compiled in the fresh VM yet.
        expected = encoded |> Base.decode64!() |> :erlang.binary_to_term()

        parameters =
          Enum.filter(Keyword.fetch!(options, :parameterize), &matches_parameters?(&1, expected))

        Keyword.put(options, :parameterize, parameters)
    end
  end

  defp matches_parameters?(parameter, expected) do
    Enum.all?(parameter, fn {key, value} -> Map.get(expected, key) == value end)
  end

  @doc false
  def run!(source, selector, options \\ []) do
    case run(source, selector, options) do
      {:ok, _output} ->
        :ok

      {:error, reason, output} ->
        raise ExUnit.AssertionError,
          message: "isolated test #{source}:#{selector} failed (#{inspect(reason)})\n#{output}"
    end
  end

  @doc false
  def child_run!(helper, source, selector) do
    Code.require_file(helper)
    # `include` alone adds a matching test but leaves untagged tests eligible.
    # Every ExUnit test has the special `:test` tag, so exclude that universe
    # first and let the exact selector opt one test back in.
    ExUnit.configure(exclude: [:test], include: selector_filter(selector))
    Code.require_file(source)

    status =
      case ExUnit.run() do
        %{failures: 0, total: total, excluded: excluded, skipped: 0}
        when total - excluded == 1 ->
          0

        result ->
          IO.puts(:stderr, "expected exactly one passing isolated test: #{inspect(result)}")
          1
      end

    # Keep the VM alive until the owner has found and reaped any OS children.
    result_path = System.fetch_env!("KOGEN_ISOLATED_RESULT")
    File.write!(result_path <> ".tmp", Integer.to_string(status))
    File.rename!(result_path <> ".tmp", result_path)
    await_cleanup(result_path <> ".ack", status)
  end

  defp await_cleanup(path, status) do
    if File.exists?(path) do
      System.halt(status)
    else
      Process.sleep(5)
      await_cleanup(path, status)
    end
  end

  defp selector_filter(selector) when is_integer(selector), do: [line: selector]
  defp selector_filter(selector) when is_atom(selector), do: [test: selector]
  defp selector_filter(selector), do: [test: String.to_atom(selector)]

  defp child_args(root, source, selector) do
    helper = Path.join(root, "test/test_helper.exs")

    code =
      "Kogen.IsolatedCase.child_run!(#{inspect(helper)}, #{inspect(source)}, #{inspect(selector)})"

    ["+S", "2:2", "+SDcpu", "1", "+SDio", "1", "-noshell"] ++
      Enum.flat_map(code_paths(), fn path -> ["-pa", path] end) ++
      ["-s", "elixir", "start_cli", "-extra", "-e", code]
  end

  defp code_paths do
    :code.get_path()
    |> Enum.map(&List.to_string/1)
    |> Enum.filter(&(Path.type(&1) == :absolute))
    |> Enum.uniq()
  end

  defp child_env(options, tmpdir) do
    configured =
      options
      |> Keyword.get(:env, [])
      |> Enum.map(fn {key, value} -> {to_string(key), to_string(value)} end)

    parameter_env =
      case Keyword.get(options, :parameters) do
        parameters when is_map(parameters) ->
          [
            {"KOGEN_ISOLATED_PARAMETERS",
             parameters |> :erlang.term_to_binary() |> Base.encode64()}
          ]

        _ ->
          []
      end

    [
      {@child_marker, "1"},
      {"ROOTDIR", List.to_string(:code.root_dir())},
      {"BINDIR", erts_bin()},
      {"EMU", "beam"},
      {"PROGNAME", "erl"},
      {"DYLD_INSERT_LIBRARIES", System.fetch_env!("KOGEN_TEST_PROCESS_GUARD")},
      {"TMPDIR", tmpdir},
      {"TMP", tmpdir},
      {"TEMP", tmpdir},
      {"MIX_BUILD_PATH", Path.join(tmpdir, "_build")},
      {"ERL_CRASH_DUMP", Path.join(tmpdir, "erl_crash.dump")},
      {"KOGEN_ISOLATED_RESULT", Path.join(tmpdir, "result")}
      | parameter_env ++ configured
    ]
    |> Enum.map(fn {key, value} -> {String.to_charlist(key), String.to_charlist(value)} end)
  end

  defp open_supervisor(args, cd, env, timeout) do
    executable = System.find_executable("python3") || raise "python3 executable was not found"
    elixir = Path.join(erts_bin(), "erlexec")

    supervisor =
      Path.join(System.fetch_env!("KOGEN_TEST_ROOT"), "test/support/isolated_process.py")

    args = [supervisor, to_string(timeout / 1_000), elixir | args]

    Port.open({:spawn_executable, String.to_charlist(executable)}, [
      :binary,
      :exit_status,
      :stderr_to_stdout,
      args: Enum.map(args, &String.to_charlist/1),
      cd: String.to_charlist(cd),
      env: env
    ])
  end

  defp erts_bin do
    Path.join([
      List.to_string(:code.root_dir()),
      "erts-#{:erlang.system_info(:version)}",
      "bin"
    ])
  end

  defp collect_port(port, output, deadline) do
    remaining = max(deadline - System.monotonic_time(:millisecond), 0)

    receive do
      {^port, {:data, data}} ->
        collect_port(port, [data | output], deadline)

      {^port, {:exit_status, status}} ->
        {status, output |> Enum.reverse() |> IO.iodata_to_binary()}
    after
      remaining ->
        # Keep the port open so its exit_status confirms supervisor cleanup.
        Port.command(port, "cancel")
        await_termination(port, output, System.monotonic_time(:millisecond) + 5_000)
    end
  end

  defp await_termination(port, output, deadline) do
    remaining = max(deadline - System.monotonic_time(:millisecond), 0)

    receive do
      {^port, {:data, data}} ->
        await_termination(port, [data | output], deadline)

      {^port, {:exit_status, 124}} ->
        {:timeout, output |> Enum.reverse() |> IO.iodata_to_binary()}

      {^port, {:exit_status, status}} ->
        {status, output |> Enum.reverse() |> IO.iodata_to_binary()}
    after
      remaining ->
        raise "isolated supervisor did not confirm cleanup; its private fixture is retained"
    end
  end

  defp private_tmpdir(options) do
    root = Path.expand(Keyword.get(options, :tmpdir_root, System.tmp_dir!()))

    path =
      Path.join(
        root,
        "kogen-isolated-#{System.pid()}-#{System.os_time(:nanosecond)}-#{System.unique_integer([:positive])}"
      )

    File.mkdir!(path)
    path
  end

  # Cleanup is best-effort here because setup is already failing. In particular,
  # a cleanup exception must never hide the error that prevented the supervisor
  # from taking ownership.
  defp cleanup_unowned_tmpdir(tmpdir) do
    File.rm_rf(tmpdir)
  rescue
    _ -> :ok
  catch
    _, _ -> :ok
  end

  defp normalize_options(options) when is_map(options), do: Map.to_list(options)
  defp normalize_options(options) when is_list(options), do: options
end
