"""Writes this shaping package only; not a product generation workflow."""
from pathlib import Path
import json
p=Path(__file__).resolve().parent.parent

def data(name,value):p.joinpath(name).write_text(json.dumps(value,indent=2)+'\n')
data('intent.yaml',{
'id':'01a09eaf-f767-75ee-8c37-a31ca9b70cb0','slug':'stage-aware-rework-budgets',
'title':'Unify Stop-hook verification with bounded rework counters','status':'draft',
'shaped_against':{'branch':'main','head':'2890d86f16c8819cfad12cbd98dbbdc8ee068b1c'},
'shaping':{'harness':'codex','model':'gpt-6-astra','effort':'low','started':'2026-09-14T06:52:07.403177Z'},
'may_change_guarded_paths':['README.md','.kogen/config.yaml','.codex/hooks.json','.codex/hooks/**','lib/kogen/build.ex','lib/kogen/build/**','lib/kogen/check.ex','lib/kogen/harness.ex','lib/kogen/intent.ex','lib/kogen/verification_policy.ex','priv/kogen/prompts/developer.md','priv/kogen/prompts/reviewer.md','priv/kogen/prompts/shaping.md','priv/kogen/prompts/execution-policy.md','scripts/check/README.md','test/kogen/**','test/support/**']})
p.joinpath('README.md').write_text('''# Unified verification and bounded rework

Start with [the contract](INTENT.md), then [scenarios](scenarios.yaml), [risks and ownership](risks.yaml), and [decision provenance](decisions.md). [intent.yaml](intent.yaml) owns current identity and approval metadata. [questions.md](questions.md) records question disposition.

Evidence: [source inspection](evidence/inspection.md), [observed stopped Build](evidence/observed-record.json), and [native Stop probe](evidence/native-stop-findings.md). The [initial Draft](evidence/historical-initial-draft/README.md) is historical, superseded proposal material. Probe sources and raw results remain editable/inspectable under evidence/; they are not production code.
''')
p.joinpath('INTENT.md').write_text('''# Unify Stop-hook verification with bounded rework counters

Current identity and approval are maintained in [intent.yaml](intent.yaml). Decisions and their provenance are in [decisions.md](decisions.md).

## Outcome and appetite

A Build that needs two verification repairs can still receive independent Review and repair its findings. Make all declared verification one hook-driven loop, and bound that loop separately from outer rework. One Developer conversation, with same-session outer resumes. The current runner used to implement this Intent still has its configured two outer resumptions; this Intent does not grant extra attempts to its own Build.

This replaces the previously accepted Stop-check/outer-target ownership split. It does not merely add counters while retaining outer execution of live. Scope includes the hook/controller boundary, counters, evidence, config and prompt/documentation alignment, and affected deterministic and native lifecycle verification. Do not implement transport recovery, parser fixes, authentication, arbitrary scheduling, stopped-Build continuation, or general process sandboxing. Do not restart or rewrite the exhausted historical Build.

## Authoritative behavior

### One verification cycle

Build preflights the frozen Approved contract and safe declared Make targets before launching the Developer. A cycle is one root Developer Stop callback: run check first, then each distinct declared non-check target in first scenario occurrence order. Stop at the first failure. Always run check, even if omitted from scenario lists. Run live only when declared; the guard's prohibited-command set always contains live and is not the executable target list.

All gate execution belongs to the Stop path under the new controller. Build consumes receipts and does not run any gate again. A failed cycle returns repair feedback within the current Developer invocation. The next Stop starts the entire sequence again, without cross-cycle caching, including when the Candidate is unchanged. A passing earlier target never grants a reset while a later required target fails.

After a complete passing cycle, Build validates matching evidence and the Developer handoff, then launches a fresh independent Reviewer. A valid accepting Review publishes by the existing commit protocol. A rework verdict resumes the exact Developer session; its next Stop runs the full sequence again. Delegated helpers do not gain gate ownership. Preserve the existing bounded PreToolUse guard and prohibition on indirect/manual gate execution.

### Two counters

1. Verification failures count failed cycles since the last complete pass. Either check or any later target failing charges exactly one. At configured allowance 2, failures 1 and 2 block Stop with corrective feedback; failure 3 records terminal exhaustion and ends the Developer invocation. Build returns failure without a fourth cycle, an outer Developer resume, Review, or publication. A complete passing cycle resets this counter to zero, even on the third cycle. Do not reset on a partial pass, a provider completion, or a new hook process.
2. Outer rework retains the existing outer_resumptions allowance (2 in this repository). With valid handoffs this is the cumulative Review-rework allowance: first and second rework verdicts resume the Developer; third stops Build. Verification progress never resets it. Preserve today's invalid-handoff correction handling under this same outer allowance; a malformed handoff does not get a new pool or unlimited corrections. Therefore malformed handoffs can consume an outer repair before Review. Retain the charge category so this is visible rather than described as a Review verdict.

These are allowances for repairs, not failure thresholds: allowance N permits N repairs and stops on failure N+1. With allowance 0, the first failure stops. Keep global outer-attempt numbering monotonic; hook cycle sequence is separately retained. With both allowances 2 and well-formed handoffs, at most three verification intervals and nine cycles occur: up to two failed cycles followed by a pass per interval, with at most three Review verdicts. Alternating check/live/Review failures cannot extend this bound. An invalid handoff consumes one of the same bounded outer transitions.

Malformed Reviewer output, cancellation, protected-input corruption, and other integrity failures do not become progress or new retry opportunities. A terminal verification-exhaustion receipt takes precedence over the provider's exit status or final prose. Provider transport recovery, if separately installed later, must neither charge nor reset these quality counters; no recovery schedule is implemented here.

### Configuration and rollout

Retain outer_resumptions as the cap on outer Developer resumptions, now that target failures are handled inside Stop. Add required nonnegative integer verification_retries to config and set it to 2 in the tracked config. Use the existing validation style: missing, negative, noninteger or otherwise invalid values fail before provider launch with the offending field named; do not infer a missing value from outer_resumptions. Update every maintained fixture/config producer that participates in this change. Preserve model/helper settings. README explains the two allowances, threshold N+1, reset point and malformed-handoff accounting. Old config files need the explicit new field; no user file is silently rewritten by runtime.

Kogen builds its own hook while the launching Build controller is already loaded. Preserve this first self-build: introduce explicit versioned unified execution context supplied by the new controller. When launched by the accepted old controller (no unified marker, but valid legacy policy/root context), the candidate hook retains legacy check-only settlement; the old controller still owns non-check targets. The new controller must always supply the new context and validate unified receipt version, so missing/corrupt unified context cannot silently downgrade. No public mode switch or additional CLI command. Prove old-controller/new-hook and new-controller/new-hook routes, without doubling live. This is transition compatibility, not an alternate long-term workflow.

### Termination and execution prerequisites

The native probe confirms that Stop continue:false terminates the invocation after three calls, but Codex reports turn.completed and exit 0 even on exhaustion. Persist the bound terminal result first, use the supported Stop response, and make Build inspect exhaustion before handoff parsing or generic rework. On first and second failures, emit supported blocking feedback with the failing target, count, remaining allowance and log locator. Do not rely on instructions asking the Developer to stop or on the process exit code alone.

The hook currently times out after 600 seconds; the existing live evaluation permits 5700 seconds. Set the unified Stop envelope to 7200 seconds so moving live does not truncate its existing fixture envelopes. A timeout, interruption, or incomplete execution never produces passing settlement. Settle owned descendants and retain failure evidence; test this with scaled short deadlines, not a two-hour test. Do not add retry or provider timeouts to unrelated routes.

Keep existing real-live prerequisites: authenticated Codex, network, installed dependencies, Python, expect, rsync, and the documented macOS tools. Do not replace live targets with fake successes. Child fixtures must have private working directories and execution context; inherited parent hook/context/budget variables must not make a nested fixture update the parent's counter or recursively run the parent's live suite. Nested public Builds initialize their own bindings. Preserve existing bounded fixture check targets and cold-offline route.

## Evidence and authority at the changed boundary

Build owns the frozen Approved input, execution target list, outer attempt token and authoritative tracking record. The root Developer Stop machinery owns cycle execution, counter state and its ordered receipts while the provider invocation is active. Neither the Developer nor helpers may modify that state. Build validates and imports it at settlement, preserving all failed-cycle history even with raw logging disabled. Do not give the hook permission to edit Approved inputs or directly rewrite the Build tracking record while its in-memory owner is active.

Bind every cycle and target receipt to the active Build/outer attempt, exact Developer session, cycle sequence and Candidate. Validate Candidate stability across gates and at settlement, target order/completeness, cycle chronology, counter increments/resets and terminal state. Missing, corrupt, stale, wrong-session or contradictory receipts cannot reach Review or publication or grant an extra allowance. Repeated callback/receipt replay cannot charge twice or execute gates after terminal exhaustion. Do not claim the shared filesystem is an adversarial security boundary; preserve the existing agent contract and runtime checks.

Retain each target's exit status, diagnostic output and required manifest/artifact snapshots at target completion, before returning any hook continuation. Preserve TargetEvidence's path/digest/schema validation and existing source-stability checks; a later Developer turn cannot replace required bytes with an assertion or a different success. Invalid target evidence remains a verification failure. Historical evidence is immutable and current successful receipts remain bound through Review/publication. Targets without a manifest keep their current behavior. Keep receipt shape consumable by scenario receipts, handoff context, independent Review, finding closure, and Complete publication; update readers together.

Logs and tracking must show failure category, both counter values/limits, each charge/reset reason, global attempt and local cycle, session/Candidate bindings and the terminal reason. Preserve finding IDs, origins, dispositions and role-specific inspected-byte snapshots. Older tracking records remain historical evidence with their original meanings; do not backfill new counters or relabel the stopped Build as recoverable/successful.

## Walkthrough and adversarial challenge

Start with a clean checkout, installed prerequisites, explicit config and an Approved Intent declaring check and live. First Stop fails check (V=1); second passes check but fails live (V=2); third passes both (V=0). Review requests repair (outer repairs used=1). That Developer repair may again fail check/live twice and pass on its third cycle. Second Review can request the second outer repair. A third accepting Review publishes; a third rework verdict stops. Every pass uses current evidence; no fourth failed cycle or fourth Review repair is available.

A superficially plausible implementation resets V whenever check passes, hiding endless live failures. Another moves live into Stop but leaves Build's live call intact. Another treats Codex exit 0 as success after continue:false, or snapshots a manifest only after the Developer has resumed. Scenarios must reject all four. Passing component tests or the shaping native transport probe alone does not establish the combined route.

## Verification workflow and completion

Before paid acceptance, run focused deterministic tests through the actual public Build controller and production hook. The fake harness must honor block/continue:false and drive multiple Stop callbacks; a fake that always returns turn.completed without dispatching hook semantics is insufficient. Assert exact target invocations, first-failure short circuit, shared charging, reset, exhaustion, handoff handling, Review count, same Developer, fresh Reviewers, bindings, findings and publication. Use check-only, duplicate/multiple target, stale/corrupt receipt, malformed handoff, artifact mutation and legacy-controller controls. Rehearse timeout/descendant cleanup with short owned fixtures.

The declared acceptance targets are check and live. The executing legacy Build retains its existing gate ownership while implementing this change; the Developer and helpers must not manually run either gate or the Stop script. Focused non-gate rehearsals remain allowed. The updated live target must exercise the new native hook-driven public Build route as well as affected existing Shape-to-Commit, Review-rework, required-evidence and cold-offline workflows. Do not recursively invoke the whole live suite from a live fixture.

The outer test driver owns ephemeral native call/Stop/session observations and retains an inspectable sequence receipt plus raw snapshots. Independent Review owns assessment of contract, Candidate, retained gate/evidence receipts and finding closure, not reconstruction of unavailable interactions. Missing native observations fail the owner-run fixture; they cannot be substituted with model claims. Refresh required-evidence forwarding through the real new hook-to-Build-to-Review-to-Complete consumer route.

Completion means declared gates pass, independent Review accepts all scenarios with no blocking findings, sources/prompts and maintained workflow docs agree on ownership, and the resulting Complete package retains the evidence. No source, test, config, hook or root README was changed during shaping.
''')
p.joinpath('decisions.md').write_text('''# Decisions and provenance

- Initial input: local follow-up 12-stage-aware-rework-budgets.md described the exhausted Build and proposed progress-sensitive allowance, explicitly leaving the algorithm unsettled.
- The Shaper then prescribed allowing two Check failures, stopping on the third, resetting after a pass, and independently stopping on the third Review failure. The assistant confirmed two different reset rules.
- The Shaper explicitly asked whether check and live share a counter; the agreed explanation was one verification counter reset only when both pass.
- The Shaper challenged the old ownership split and proposed check followed by live in Stop. The final presented plan generalized this to the Intent's ordered targets, first-failure short circuit, third-failure termination, and separate bounded Review rework. This supersedes the initial one-time milestone-reset proposal and the previous split-owner contract for new-controller runs.
- The Shaper explicitly instructed: “Ok, let's go. Finish shaping this. I approve.” This approves the presented unified-loop scope and two-counter policy in this conversation; it does not authorize implementation during shaping.
- Later investigation exposed invalid handoffs. The Shaper challenged why these occur, without selecting a new policy. The controller explained model-generated protocol failures and withdrew the proposed expansion: preserve existing bounded outer-resumption handling. This is preservation from current Build.rework/4 and validate_handoff/6, not an invented third allowance or a claim that the Shaper chose one of the offered options.
- Engineering details derived from source: retain outer_resumptions for outer repairs; explicitly configure verification_retries=2 using existing required-field validation conventions; retain legacy-controller compatibility for the first self-build; extend Stop's envelope to accommodate the already maintained live envelopes; snapshot target evidence before any continuation. These implement/preserve the agreed behavior and grant no new product scope.

Original id, baseline and shaping provenance remain unchanged. Historical initial Draft files are retained under evidence/historical-initial-draft/. Current approval metadata is owned by intent.yaml.
''')
p.joinpath('questions.md').write_text('''# Question disposition

No unresolved product choice remains in the scoped contract.

- Reset policy: settled by the Shaper's two-counter instructions; initial milestone-reset alternatives are superseded.
- Target ownership: settled by the Shaper's Stop sequencing proposal and explicit approval of the presented plan.
- Invalid handoff: no new allowance was selected. Preserve the existing outer-resumption handling as recorded in decisions.md. This means malformed handoffs can consume a Review-side outer repair; they are identified separately in evidence and diagnostics.
- Configuration: retain the existing outer cap and explicitly add the verification allowance using the repository's required-field convention; runtime does not migrate user files or infer missing values.

The native callback question was probed, not deferred. Production implementation and full combined-route acceptance remain work for the later Developer and gate owners, not unresolved shaping decisions.
''')
S=[]
def s(i,g,w,t,x,e,live=False):S.append(dict(id=i,given=g,when=w,then=t,wrong_result=x,verified_by=['check','live'] if live else ['check'],evidence=e))
s('hook-ownership','a new-controller Build declares check and ordered non-check targets with duplicates','the root Developer attempts to stop','Stop alone runs check then distinct declared targets in first occurrence order; Build imports receipts and does not rerun them; check-only Intents never run undeclared live','the prohibited-target list is executed or Build duplicates live','Production-hook public fixture asserts executable owner and exact sequence; native public Build driver retains calls.',True)
s('shared-failures','verification_retries is 2 and check fails once followed by live failing after check passes','the next complete cycle also fails any required target','V progresses 1,2,3 without an intermediate reset and Build terminates with no fourth callback/resume/Review','each target has its own allowance or passing check resets live failures','Mixed-target deterministic hook/Build history and negative fourth-call marker.')
s('third-pass','two cycles have failed before the first Review','the third cycle passes every gate and Review requests repair','V resets to zero, outer repair 1 resumes the same Developer, and another two verification failures followed by complete pass are allowed','the old total counter rejects the first Review repair','Combined public Build fixture and native live route retain per-cycle receipts, same session and fresh Review.',True)
s('outer-limit','all handoffs are valid and full verification passes between Review verdicts','Review returns rework three times','the first two verdicts resume the Developer and the third ends Build, preserving findings; V resets never reset the outer counter','Review retries are renewed by each passing verification','Deterministic three-Review trace, no fourth Reviewer/Developer resume and no publication; accepting-third control.')
s('handoff-preservation','verification passes but the final Developer response lacks required contract fields or has the wrong token','Build validates the handoff','invalid handoff corrections remain charged to outer_resumptions, never reach Review as valid claims, never create a third allowance, and exhaust after two repairs at value 2','successful tests are treated as proof the handoff must be valid or malformed messages retry forever','Real Contract.handoff public fixture: repeated malformed and mixed malformed/Review rework controls.')
s('regression-bound','Review-directed changes regress check or a later target','repeated repairs alternate targets and Review','every Stop starts all gates afresh, partial target success never resets V, and both allowances enforce the finite bound even with unchanged Candidate','the loop skips previously passing targets or refreshes outer budget','Table-driven actual-controller sequences include nine-cycle upper-bound case and unchanged-Candidate failures.')
s('native-exhaustion','the native Developer receives two Stop blocks followed by a third verification failure','the hook writes terminal exhaustion then returns continue:false','the invocation ends and Build reports exhaustion even if Codex exits 0 with turn.completed; no additional development/Review occurs','Build interprets native successful exit as verification success or generic resumable failure','New production-hook native fixture and owner-retained invocation trace; shaping probe supplies only callback prerequisite evidence.',True)
s('evidence-forwarding','a hook-owned target emits a valid required manifest and artifact','it completes and a later target fails before a subsequent repair cycle','manifest and required bytes were captured before continuation, retained across failures and forwarded through Build/Review/Complete; missing/changed/invalid sources fail existing evidence validation','artifact collection waits until after Developer continuation or loses uncited bytes','Actual TargetEvidence controls and real required-evidence fixture through the new consumer chain.',True)
s('binding-integrity','current and stale/wrong-session/corrupt/replayed cycle receipts exist as separate controls','Build settles the invocation or a callback repeats after exhaustion','only complete ordered fresh bound evidence settles; chronology/counters are checked, exhaustion is latched, and replay cannot rerun gates or charge twice','a stale pass, missing cycle or overwritten failed record grants acceptance or allowance','Public fixture with receipt corruption, Candidate mutation during gates, repeat callback and no-extra-dispatch markers.')
s('preserved-authority','Build reworks and later accepts a verified Candidate','history and Complete evidence are produced','same Developer, fresh independent Review, finding origins/closures, role-specific snapshots and all failed-cycle history remain inspectable even without raw logs','new counters erase failed attempts or grant the Developer control of authoritative records','Tracking and publication fixtures plus native lifecycle audit of exact sessions.',True)
s('config-contract','explicit verification_retries and outer_resumptions are supplied or invalid/missing','Build preflights configuration','both accept nonnegative integers, invalid config fails before provider dispatch, 0 stops first failure and 2 permits two repairs; unrelated profile settings remain unchanged','a missing allowance is silently invented or interpreted as total attempts','Config/parser and public precondition tests, config producer audit, zero/two allowance controls.')
s('self-build-transition','the accepted old controller launches a Candidate containing the new hook, or the new controller launches it','verification runs','valid legacy launch retains check-only hook and old outer targets, while versioned new launch runs all targets only in Stop; corrupted new context cannot downgrade','the first self-build fails for absent new context or runs live twice','Bounded actual old-controller/new-hook and new-controller/new-hook fixtures with ordered dispatch receipts.')
s('lifetime-isolation','live runs inside Stop and starts nested private fixtures under inherited environment','fixtures execute, or a scaled timeout interrupts their owned processes','live keeps its existing time envelopes, nested counters/roots stay private, descendants settle, incomplete hooks cannot pass, and no full live recursion occurs','600-second cutoff truncates supported live work or nested Build rewrites parent state','Production timeout/cleanup controls with short deadlines and actual native/cold-offline/live workflow evidence.',True)
s('gate-guard','Developer or delegated helper attempts a protected explicit Make/Stop invocation','PreToolUse dispatches the request','existing covered forms remain denied before execution while focused non-gate work and genuine root Stop callbacks work','moving ownership grants manual gate permission or helper Stops run parent gates','Production guard regression plus public root/helper-context fixture with forbidden execution markers.')
data('scenarios.yaml',S)
def own(paths,exists,owner,operation,mutation,validation,git,upgrade):return dict(paths=paths,when_exists=exists,owner_after_creation=owner,owner_during_operation=operation,permitted_mutation=mutation,validation=validation,git_state=git,upgrade_behavior=upgrade)
data('risks.yaml',[
{'id':'gate-state-lifetime','scenario_ids':['shared-failures','third-pass','native-exhaustion','binding-integrity','preserved-authority','lifetime-isolation'],'description':'In-turn hook processes restart, while Build owns tracking in memory. Counter reset, concurrent nested access, or losing exhaustion can bypass the finite bound. Hooks must use scoped state and preserve every cycle; Build imports and validates rather than sharing its authoritative tracking writer.', 'ownership':[own('.kogen/runtime verification state, per-cycle logs/receipts and execution context for this Build','Fresh scoped state exists before the new-controller Developer launch; legacy state remains only on the legacy route. Existing conflicting or malformed active context is never silently adopted.','Build machinery initializes context; root Stop machinery creates its execution receipts.','Build owns frozen context; root Stop owns cycle state during invocation; Build owns validation and imported snapshots at settlement.','Only owner initialization, ordered append/atomic settlement, and validated pass reset; no Developer/helper edits, no reset of Review budget.','Version, Build/attempt/session/Candidate binding, cycle order, target completeness, counter transitions, terminal latch, private root and cleanup controls.','Ignored runtime state; retain concise owned evidence in tracked Complete output on success.','Old records remain historical; new runs create fresh state. Preserve legacy-controller handshake during self-build; never migrate a stopped record.'),own('.kogen/runtime/scenario-tracking/<build-id>/record.json and successful Complete evidence','Tracking is created exclusively per Build, as today; Complete output only on accepted publication.','Build controller.','Build controller; Reviewer and Developer are readers under existing snapshot rules.','Append attempt/cycle evidence through Build updates, preserving prior findings, history and byte snapshots; normal publication only.','Existing exact-byte owner checks, current bindings, publication/failure restoration and new sequence assertions.','Runtime ignored; Complete evidence tracked with accepted commit.','Retain old schema meaning and bytes; add versioned/unambiguous current budget evidence, not backfilled claims.')]},
{'id':'target-artifact-lifetime','scenario_ids':['evidence-forwarding','binding-integrity','preserved-authority'],'description':'Target artifacts can disappear or change before Build regains control. Snapshot inside the hook completion path and preserve the existing source-stability contract; retained bytes do not excuse source mutation.', 'ownership':[own('Required target manifests/artifacts and their per-cycle retained snapshots under existing target-owned runtime paths','Targets create outputs at execution; only regular, safe declared files with verified digest are eligible.','Target creates its outputs; Stop machinery captures bound immutable evidence.','Target owns production until binding; machinery owns frozen snapshots and requires bound source stability through the existing lifetime.','No Developer replacement of bound artifacts; target reruns use noncolliding output paths when prior evidence is still bound.','Existing TargetEvidence frame/schema/path/digest validation plus new hook-to-controller consumer tests and mutation/deletion controls.','Ignored target runtime artifacts; copied evidence tracked only through normal Complete publication.','Preserve existing manifest contract and no-frame behavior; do not reinterpret historical snapshots.')]},
{'id':'configuration-and-self-build','scenario_ids':['config-contract','self-build-transition','hook-ownership','gate-guard'],'description':'The launching controller predates hook edits and the prohibition set differs from the execution set. Explicit protocol selection and coordinated config producers prevent silent downgrade or duplicate live.', 'ownership':[own('.kogen/config.yaml, .codex/hooks.json and tracked hook helpers','Existing tracked files at baseline; Developer edits only during the authorized later Build.','Repository maintainer through accepted Build.','Repository-owned configuration and machinery; no transition to user-owned seed is introduced.','Add explicit verification allowance and coordinated hook protocol/timeout changes; preserve other settings and bounded gate denial.','Required-field preflight, old/new controller handshake, declared target selection, direct dispatch guard and actual native route.','Tracked source/config; no runtime rewrites or hidden migration.','Missing new config key gives actionable validation error; documented repository update adds it. Old running controller compatibility is explicit and bounded.')]}
])
data('references.yaml',[
{'path':'../../../../runtime/shaping-followups/serial-optimization/12-stage-aware-rework-budgets.md','description':'Initiating local follow-up; historical input, not approval.'},
{'path':'../../complete/automated-verification-ownership/INTENT.md','description':'Prior owner split and preserved bounded gate guard; new-controller split is superseded by this Intent.'},
{'path':'../../complete/target-evidence-retention/intent.yaml','description':'Required-artifact evidence preservation contract.'},
{'url':'https://learn.chatgpt.com/docs/hooks','description':'Official Stop response and timeout documentation; native probe confirms installed-client behavior.'}
])
print('Draft files written; approval bookkeeping not yet applied.')
