## Provider-denied validation of the fixtures no `prepare` generates
## (scenario offline-fixture-validation). The three targets that declare a
## `prepare` (live-reviewer-rework, live-shaping-quality, live-shaping-smoke)
## validate their own generated fixtures inside that prepare, recorded by
## scripts/check/rehearsals.exs. This stage covers the rest of the selected
## route: the live-native compatibility fixture, generated by the same
## `Kogen.Codex.Compatibility.prepare_fixture/2` the live owner calls.
## (live-shape-to-build and live-general generate their fixtures inside their
## own ExUnit bodies; see scripts/check/README.md for that stated gap.)
##
## Provider access is denied for the whole process before anything is
## generated: credentials removed, `claude`/`codex` on PATH resolve to
## refusing shims, KOGEN_PROVIDERS_DENIED=1. Standalone:
##   MIX_BUILD_PATH=... mix run scripts/check/fixture_validation.exs
Code.require_file("test/support/fixture_validation.ex")
Code.require_file("test/support/route_config.ex")

shims =
  Path.join(
    System.tmp_dir!(),
    "kogen-fixture-validation-shims-#{System.unique_integer([:positive])}"
  )

File.mkdir_p!(shims)

for name <- ~w(claude codex) do
  path = Path.join(shims, name)

  File.write!(
    path,
    "#!/bin/sh\necho \"fixture validation denied a provider launch: #{name} $*\" >&2\nexit 97\n"
  )

  File.chmod!(path, 0o755)
end

for name <-
      ~w(ANTHROPIC_API_KEY ANTHROPIC_AUTH_TOKEN ANTHROPIC_BASE_URL CLAUDE_CODE_OAUTH_TOKEN
         OPENAI_API_KEY OPENAI_BASE_URL AZURE_OPENAI_API_KEY CODEX_API_KEY),
    do: System.delete_env(name)

System.put_env("PATH", shims <> ":" <> (System.get_env("PATH") || ""))
System.put_env("KOGEN_PROVIDERS_DENIED", "1")
Kogen.FixtureValidation.require_denied!()

codex_root =
  Path.join(
    System.tmp_dir!(),
    "kogen-fixture-validation-codex-#{System.unique_integer([:positive])}"
  )

System.put_env("KOGEN_CODEX_ROOT", codex_root)

result =
  try do
    config = Kogen.RouteConfig.codex_route!()

    case Kogen.Codex.Compatibility.prepare_fixture(File.cwd!(), config) do
      {:ok, fixture, _evidence, discovery} ->
        spec = %{
          "kind" => "live-native-compatibility",
          "label" => "compatibility-fixture",
          "required" => [
            "README.md",
            "PROJECT_GUIDANCE.md",
            "Makefile",
            "environment-receipt.py",
            ".codex/hooks.json",
            ".codex/hooks/verification_policy.py",
            ".codex/hooks/environment.py",
            ".agents/skills/project-context/SKILL.md"
          ],
          "json" => [".codex/hooks.json"],
          # Seeded discovery context embeds run-specific paths and timestamps.
          "digest_exclude" => [".kogen-discovery-context.json"],
          "makefile_targets" => ["check"]
        }

        with {:ok, record} <- Kogen.FixtureValidation.validate(fixture, spec),
             true <- File.dir?(discovery["home"]) or {:error, ["discovery home is missing"]} do
          {:ok, record}
        else
          {:error, reasons} -> {:error, reasons}
        end

      {:error, reason} ->
        {:error, ["compatibility fixture generation failed: " <> inspect(reason)]}
    end
  rescue
    error -> {:error, ["compatibility fixture generation raised: " <> Exception.message(error)]}
  after
    File.rm_rf(codex_root)
    File.rm_rf(shims)
  end

case result do
  {:ok, record} ->
    IO.puts("KOGEN_FIXTURE_VALIDATION\t" <> Jason.encode!(record))

    if path = System.get_env("KOGEN_FIXTURE_VALIDATION_RECEIPT"),
      do: Kogen.FixtureValidation.append_record!(path, record)

  {:error, reasons} ->
    for reason <- reasons, do: IO.puts(:stderr, "fixture validation failed: " <> reason)
    System.halt(1)
end
