#!/usr/bin/env python3
"""hook_registrations.py — Parse HOOK-MANIFEST headers and generate hook registration JSONs.

Usage:
    python3 templates/generator/hook_registrations.py \
        --hooks-dir harnesses/claude/hooks \
        --output-settings templates/claude-code-settings.json

Algorithm:
    1. Find all .sh files (excluding _test.sh and run-tests.sh) in --hooks-dir.
    2. Parse HOOK-MANIFEST header block (event, matcher, surface, signal, role).
    3. Validate declared signal appears in script body.
    4. Build user_global and per_call_inspector lists.
    5. Emit --output-settings (user_global entries replace manifest-driven hook events;
       non-manifest-driven events preserved verbatim from existing JSON).

Non-manifest-driven hook events (preserved verbatim from existing settings.json):
    PostToolUse, UserPromptSubmit, SessionStart, SessionEnd

These contain inline bash commands that cannot be expressed as hook scripts,
so they are never regenerated by this tool.

Manifest-driven hook events (fully regenerated):
    PreToolUse, SubagentStop, Stop, PostToolUseFailure

Hook ordering within each event:
    Sorted alphabetically by filename for deterministic output.

Pi TS handler parity:
    When --pi-extension-dir is provided, validates that every Pi-targeted hook
    has a matching TypeScript handler in <pi-extension-dir>/src/hooks/.
"""

import argparse
import json
import os
import re
import sys
from pathlib import Path


def dumps_compact(obj, indent=2, print_width=80):
    """json.dumps with indent=2 but keeps flat string-only arrays on one line when they fit within print_width."""
    raw = json.dumps(obj, indent=indent)

    def collapse_if_fits(m):
        collapsed = "[" + ", ".join(s.strip() for s in m.group(1).split(",\n")) + "]"
        # Measure indent of the opening bracket by looking at chars before the match
        start = m.start()
        line_start = raw.rfind("\n", 0, start) + 1
        indent_len = start - line_start
        if indent_len + len(collapsed) <= print_width:
            return collapsed
        return m.group(0)

    # Collapse arrays that contain only quoted strings (no nested objects/arrays)
    return re.sub(
        r'\[\n\s+("(?:[^"\\]|\\.)*"(?:,\n\s+"(?:[^"\\]|\\.)*")*)\n\s+\]',
        collapse_if_fits,
        raw,
    )

REQUIRED_FIELDS = {"event", "matcher", "surface", "signal", "role"}
VALID_SURFACES = {"user_global", "per_call_inspector", "both"}
VALID_SIGNALS = {"AGENT_TYPE", "CLAUDE_ROLE", "CLAUDE_ROLE_FAMILY", "none"}
VALID_HARNESSES = {"claude_code", "pi"}

# Hook events managed entirely by manifests — regenerated from script headers.
MANIFEST_DRIVEN_EVENTS = {"PreToolUse", "SubagentStop", "Stop", "PostToolUseFailure"}

# Hook events with inline commands — preserved verbatim from existing settings.json.
PRESERVED_EVENTS = {"PostToolUse", "UserPromptSubmit", "SessionStart", "SessionEnd"}

# Canonical event ordering in output settings.json.
EVENT_ORDER = [
    "PostToolUse",
    "PostToolUseFailure",
    "UserPromptSubmit",
    "SessionStart",
    "SessionEnd",
    "Stop",
    "SubagentStop",
    "PreToolUse",
]


def parse_manifest(script_path: Path) -> dict:
    """Parse HOOK-MANIFEST header block from a .sh file.

    Returns dict with keys: event, matcher, surface, signal, role, filename.
    Exits non-zero if required fields are missing or malformed.
    """
    content = script_path.read_text()
    lines = content.splitlines()

    in_manifest = False
    fields: dict = {}
    for line in lines:
        stripped = line.strip()
        if stripped == "# HOOK-MANIFEST:":
            in_manifest = True
            continue
        if in_manifest:
            m = re.match(r"^#\s+(\w+):\s+(.+)$", stripped)
            if m:
                key = m.group(1)
                val = m.group(2).strip()
                if key in REQUIRED_FIELDS:
                    fields[key] = val
                elif key == "harnesses":
                    fields["harnesses"] = val
                # Continue scanning for optional fields (harnesses may follow required).
            elif stripped == "#" or stripped == "":
                # Blank comment line or empty line → end of manifest key-value block.
                # Stop here to avoid parsing prose comment lines that may accidentally
                # match the key: value regex and overwrite already-parsed fields.
                break
            elif not stripped.startswith("#"):
                # Non-comment line → manifest block ended
                break

    missing = REQUIRED_FIELDS - set(fields.keys())
    if missing:
        print(
            f"ERROR: {script_path.name} is missing HOOK-MANIFEST fields: {sorted(missing)}",
            file=sys.stderr,
        )
        sys.exit(1)

    if fields["surface"] not in VALID_SURFACES:
        print(
            f"ERROR: {script_path.name} has invalid surface '{fields['surface']}'. Must be one of: {VALID_SURFACES}",
            file=sys.stderr,
        )
        sys.exit(1)

    if fields["signal"] not in VALID_SIGNALS:
        print(
            f"ERROR: {script_path.name} has invalid signal '{fields['signal']}'. Must be one of: {VALID_SIGNALS}",
            file=sys.stderr,
        )
        sys.exit(1)

    # Parse and validate optional harnesses field.
    # "all" or absent → None (ships everywhere, default).
    # Explicit list (e.g. "claude_code") → list of tokens.
    if "harnesses" in fields:
        raw_val = fields["harnesses"]
        if raw_val.strip() == "all":
            fields["harnesses"] = None  # "all" is shorthand for ships-everywhere
        else:
            tokens = [t.strip() for t in raw_val.split(",")]
            invalid = [t for t in tokens if t not in VALID_HARNESSES]
            if invalid:
                print(
                    f"ERROR: {script_path.name} has invalid harnesses tokens: {invalid}. Must be from: {VALID_HARNESSES} or 'all'",
                    file=sys.stderr,
                )
                sys.exit(1)
            fields["harnesses"] = tokens
    else:
        fields["harnesses"] = None  # None = ships everywhere (default)

    fields["filename"] = script_path.name
    return fields


def validate_role_match(script_path: Path, manifest: dict) -> None:
    """Verify that literal role values appear in script body as guard patterns.

    For literal role values (no *, |, not in {*, all}):
      - body must contain [ "$AGENT_TYPE" = "<literal>" ]
        OR case "$AGENT_TYPE" in ... <literal>) ;;
    For glob roles (planner-*, developer-*):
      - body must contain case "$AGENT_TYPE" in <glob>) ;;
        OR printf '%s' "$AGENT_TYPE" | grep -qE '^<prefix>-'
    For wildcard roles (*, all):
      - no check required.
    Exits non-zero on mismatch (prints script name + pattern detail).
    """
    signal = manifest["signal"]
    # Only validate AGENT_TYPE signal hooks — others use CLAUDE_ROLE etc.
    if signal != "AGENT_TYPE":
        return

    content = script_path.read_text()
    role_raw = manifest["role"]

    # Split multi-value roles on |
    role_tokens = [t.strip() for t in role_raw.split("|")]

    for token in role_tokens:
        # Universal wildcards — no body check needed
        if token in ("*", "all"):
            continue

        # Glob role (ends with -*)
        if token.endswith("-*"):
            prefix = token[:-2]  # strip trailing -*
            # Accept: case ... in <prefix>-*) or grep -qE '^<prefix>-'
            glob_case = f"case \"$AGENT_TYPE\" in"
            glob_pattern = f"{prefix}-"
            if glob_case not in content or glob_pattern not in content:
                # Also accept grep-based guard
                grep_pattern = f"'^{prefix}-'"
                if grep_pattern not in content and glob_pattern not in content:
                    print(
                        f"ERROR: {script_path.name} declares role: {token} (glob) but body "
                        f"does not contain case \"$AGENT_TYPE\" in ... {prefix}-*) or grep '^{prefix}-'",
                        file=sys.stderr,
                    )
                    sys.exit(1)
            continue

        # Literal role with | — multi-case, expect case statement or helper fn
        if "|" in role_raw:
            # Each token in a multi-value role must appear in a case statement,
            # OR the hook uses require_inspector_agent_type (covers all inspector roles).
            # Case patterns can be: token) OR token | othertoken)
            inspector_fn = "require_inspector_agent_type"
            token_in_case = f'{token})' in content or f'{token} |' in content or f'{token} )' in content
            if (
                f'"{token}"' not in content
                and not token_in_case
                and not ("inspector" in token and inspector_fn in content)
            ):
                print(
                    f"ERROR: {script_path.name} declares role: {token} but body "
                    f"does not contain \"{token}\" or {token}) in a case statement",
                    file=sys.stderr,
                )
                sys.exit(1)
            continue

        # Single literal role — accept [ "$AGENT_TYPE" = "<literal>" ] (equality),
        # [ "$AGENT_TYPE" != "<literal>" ] (inequality guard), case statement,
        # or require_inspector_agent_type (for inspector roles)
        eq_check = f'[ "$AGENT_TYPE" = "{token}" ]'
        ne_check = f'[ "$AGENT_TYPE" != "{token}" ]'
        case_check = f'{token})'
        inspector_fn = "require_inspector_agent_type"
        if (
            eq_check not in content
            and ne_check not in content
            and case_check not in content
            and not ("inspector" in token and inspector_fn in content)
        ):
            print(
                f"ERROR: {script_path.name} declares role: {token} but body "
                f"does not contain [ \"$AGENT_TYPE\" = \"{token}\" ] or {token}) in a case statement",
                file=sys.stderr,
            )
            sys.exit(1)


def validate_signal(script_path: Path, manifest: dict) -> None:
    """Verify declared signal appears in script body.

    Exits non-zero if signal declared but not referenced in body.

    Signal semantics:
      CLAUDE_ROLE         — body must reference CLAUDE_ROLE literal.
      CLAUDE_ROLE_FAMILY  — body must call resolve_role() (from _role.sh); supports CLAUDE_ROLE,
                            PI_ROLE with unified precedence.
      AGENT_TYPE          — body must reference AGENT_TYPE or require_inspector_agent_type.
      none                — no signal check.
    """
    signal = manifest["signal"]
    if signal == "none":
        return

    content = script_path.read_text()
    if signal == "AGENT_TYPE":
        if "AGENT_TYPE" not in content and "require_inspector_agent_type" not in content:
            print(
                f"ERROR: {script_path.name} declares signal: AGENT_TYPE but body does not reference AGENT_TYPE or require_inspector_agent_type",
                file=sys.stderr,
            )
            sys.exit(1)
    elif signal == "CLAUDE_ROLE":
        if "CLAUDE_ROLE" not in content:
            print(
                f"ERROR: {script_path.name} declares signal: CLAUDE_ROLE but body does not reference CLAUDE_ROLE",
                file=sys.stderr,
            )
            sys.exit(1)
    elif signal == "CLAUDE_ROLE_FAMILY":
        if "resolve_role" not in content:
            print(
                f"ERROR: {script_path.name} declares signal: CLAUDE_ROLE_FAMILY but body does not call resolve_role (sourced from _role.sh)",
                file=sys.stderr,
            )
            sys.exit(1)
def collect_hooks(hooks_dir: Path) -> list:  # type: ignore[type-arg]
    """Find all .sh files (excluding _test.sh, run-tests.sh, and _*.sh helpers) and parse manifests.

    Files starting with '_' are library helpers sourced by hook scripts, not registered hooks.
    Canonical example: _role.sh (shared resolve_role() helper).
    """
    hooks = []
    for sh_file in sorted(hooks_dir.glob("*.sh")):
        if sh_file.name.endswith("_test.sh"):
            continue
        if sh_file.name == "run-tests.sh":
            continue
        # Skip library helpers: files whose basename starts with '_'.
        # These are sourced by hook scripts and must not appear in settings.json.
        if sh_file.name.startswith("_"):
            continue
        manifest = parse_manifest(sh_file)
        validate_signal(sh_file, manifest)
        validate_role_match(sh_file, manifest)
        hooks.append(manifest)
    return hooks


def parse_subagent_frontmatter(subagent_path: Path) -> dict:
    """Parse YAML frontmatter between `---` lines inside `{% if tool.yaml_frontmatter %}` block.

    Returns dict with at least `name` key. Exits non-zero if `name` not found.
    """
    content = subagent_path.read_text()
    lines = content.splitlines()

    in_block = False
    in_frontmatter = False
    frontmatter_lines = []

    for line in lines:
        stripped = line.strip()
        if not in_block and "{% if tool.yaml_frontmatter %}" in stripped:
            in_block = True
            continue
        if in_block and not in_frontmatter and stripped == "---":
            in_frontmatter = True
            continue
        if in_frontmatter:
            if stripped == "---":
                break
            frontmatter_lines.append(line)

    result: dict = {}
    for fl in frontmatter_lines:
        m = re.match(r"^(\w[\w-]*):\s*(.+)$", fl.strip())
        if m:
            result[m.group(1)] = m.group(2).strip()

    if "name" not in result:
        print(
            f"ERROR: {subagent_path.name} has no `name:` in YAML frontmatter",
            file=sys.stderr,
        )
        sys.exit(1)

    return result




def build_hook_entry(manifest: dict) -> dict:
    """Build a Claude Code settings.json hook entry."""
    return {
        "type": "command",
        "command": f"$HOME/.claude/hooks/{manifest['filename']}",
    }


def load_existing_settings(settings_path: Path, existing_settings_path=None) -> dict:
    """Load existing settings.json for preserved-event extraction.

    If --existing-settings is provided, read from there (used by hook-parity to
    supply the committed file as the source of preserved events while writing output
    to /tmp). Otherwise, read from settings_path itself.
    """
    source = existing_settings_path if existing_settings_path is not None else settings_path
    if source.exists():
        return json.loads(source.read_text())
    return {}


def group_by_event(hooks: list) -> dict:
    """Group hooks by event type, sorted alphabetically by filename within each event."""
    groups: dict = {}
    for h in sorted(hooks, key=lambda x: x["filename"]):
        event = h["event"]
        groups.setdefault(event, [])
        groups[event].append(h)
    return groups


def regenerate_settings(
    existing: dict, user_global_hooks: list, settings_path: Path
) -> None:
    """Regenerate the hooks section of settings.json with user_global hooks.

    Preserves all top-level non-hooks keys verbatim.
    Preserves PRESERVED_EVENTS hook entries verbatim.
    Rebuilds MANIFEST_DRIVEN_EVENTS from user_global_hooks.
    """
    # Start with a copy of everything except hooks
    settings = {k: v for k, v in existing.items() if k != "hooks"}

    existing_hooks = existing.get("hooks", {})
    new_hooks: dict = {}

    # Preserve non-manifest-driven events verbatim
    for evt in PRESERVED_EVENTS:
        if evt in existing_hooks:
            new_hooks[evt] = existing_hooks[evt]

    # Build manifest-driven events from user_global hooks
    by_event = group_by_event(user_global_hooks)

    for evt in MANIFEST_DRIVEN_EVENTS:
        if evt not in by_event:
            continue
        entries = []
        for h in by_event[evt]:
            hook_cmd = build_hook_entry(h)
            matcher = h["matcher"]

            if evt == "Stop" and matcher == "*":
                # Stop hooks with wildcard matcher: no matcher key
                entries.append({"hooks": [hook_cmd]})
            elif evt == "SubagentStop":
                entries.append({"matcher": matcher, "hooks": [hook_cmd]})
            elif evt == "PostToolUseFailure":
                entries.append({"matcher": matcher, "hooks": [hook_cmd]})
            else:
                entries.append({"matcher": matcher, "hooks": [hook_cmd]})
        new_hooks[evt] = entries

    # Assemble in canonical order
    ordered_hooks: dict = {}
    for evt in EVENT_ORDER:
        if evt in new_hooks:
            ordered_hooks[evt] = new_hooks[evt]
    # Append any remaining events not in EVENT_ORDER
    for evt in new_hooks:
        if evt not in ordered_hooks:
            ordered_hooks[evt] = new_hooks[evt]

    settings["hooks"] = ordered_hooks
    settings_path.write_text(dumps_compact(settings) + "\n")
    print(f"Wrote {settings_path}")


def validate_pi_ts_handlers(pi_hooks: list, pi_extension_dir: Path) -> None:
    """Verify every Pi-targeted hook has a matching TypeScript handler.

    For each hook in pi_hooks, derives handler name = filename without .sh extension,
    then checks <pi_extension_dir>/src/hooks/<name>.ts exists.
    Exits non-zero with a descriptive message listing all missing handlers.
    """
    hooks_src_dir = pi_extension_dir / "src" / "hooks"
    missing = []
    for h in sorted(pi_hooks, key=lambda x: x["filename"]):
        name = h["filename"][:-3] if h["filename"].endswith(".sh") else h["filename"]
        ts_path = hooks_src_dir / f"{name}.ts"
        if not ts_path.exists():
            missing.append(f"  {h['filename']} → expected {ts_path}")

    if missing:
        print(
            "ERROR: Pi handler parity check FAILED. "
            f"The following {len(missing)} hook(s) have no TypeScript handler in "
            f"{hooks_src_dir}:\n" + "\n".join(missing) + "\n"
            "Add the missing .ts handler(s) before running make install.",
            file=sys.stderr,
        )
        sys.exit(1)

    print(f"Pi TS handler parity: OK ({len(pi_hooks)} hooks matched)")




def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate hook registration JSONs from HOOK-MANIFEST headers"
    )
    parser.add_argument(
        "--hooks-dir", required=True, help="Directory containing .sh hook files"
    )
    parser.add_argument(
        "--output-settings",
        required=True,
        help="Path to write regenerated claude-code-settings.json",
    )
    parser.add_argument(
        "--existing-settings",
        help="Path to read existing settings from (for preserved events). Defaults to --output-settings.",
    )
    parser.add_argument(
        "--pi-extension-dir",
        help="Path to Pi extension package root (validates TS handler parity for Pi-targeted hooks)",
    )
    args = parser.parse_args()

    hooks_dir = Path(args.hooks_dir)
    if not hooks_dir.is_dir():
        print(f"ERROR: --hooks-dir '{hooks_dir}' is not a directory", file=sys.stderr)
        sys.exit(1)

    settings_path = Path(args.output_settings)
    existing_settings_path = Path(args.existing_settings) if args.existing_settings else None

    # Collect and parse all hooks
    all_hooks = collect_hooks(hooks_dir)

    # Partition by surface
    user_global_hooks = [h for h in all_hooks if h["surface"] in ("user_global", "both")]
    per_call_hooks = [h for h in all_hooks if h["surface"] in ("per_call_inspector", "both")]

    print(
        f"Found {len(all_hooks)} hooks: {len(user_global_hooks)} user_global, {len(per_call_hooks)} per_call_inspector"
    )

    # Regenerate settings.json
    existing = load_existing_settings(settings_path, existing_settings_path)
    regenerate_settings(existing, user_global_hooks, settings_path)

    # Validate Pi TS handler parity if --pi-extension-dir provided
    if args.pi_extension_dir:
        pi_hooks = [h for h in all_hooks if "pi" in (h.get("harnesses") or [])]
        validate_pi_ts_handlers(pi_hooks, Path(args.pi_extension_dir))

    print("hook_registrations.py: OK")


if __name__ == "__main__":
    main()
