#!/usr/bin/env python3
"""hook_registrations.py — Parse HOOK-MANIFEST headers and generate hook registration JSONs.

Usage:
    python3 templates/generator/hook_registrations.py \
        --hooks-dir harnesses/claude/hooks \
        --output-settings templates/claude-code-settings.json \
        --combobulate-dir /path/to/combobulate

Algorithm:
    1. Find all .sh files (excluding _test.sh and run-tests.sh) in --hooks-dir.
    2. Parse HOOK-MANIFEST header block (event, matcher, surface, signal, role).
    3. Validate declared signal appears in script body.
    4. Build user_global and per_call_inspector lists.
    5. Emit --output-settings (user_global entries replace manifest-driven hook events;
       non-manifest-driven events preserved verbatim from existing JSON).
    6. Emit priv/claude_config/inspector_settings.json and hook_manifest.json
       (if --combobulate-dir provided).

Non-manifest-driven hook events (preserved verbatim from existing settings.json):
    PostToolUse, UserPromptSubmit, SessionStart, SessionEnd

These contain inline bash commands that cannot be expressed as hook scripts,
so they are never regenerated by this tool.

Manifest-driven hook events (fully regenerated):
    PreToolUse, SubagentStop, Stop, PostToolUseFailure

Hook ordering within each event:
    Sorted alphabetically by filename for deterministic output.
"""

import argparse
import hashlib
import json
import os
import re
import sys
from pathlib import Path


def dumps_compact(obj, indent=2, print_width=80):
    """json.dumps with indent=2 but keeps flat string-only arrays on one line when they fit within print_width."""
    raw = json.dumps(obj, indent=indent)

    def collapse_if_fits(m):
        collapsed = "[" + ", ".join(s.strip() for s in m.group(1).split(",\n")) + "]"
        # Measure indent of the opening bracket by looking at chars before the match
        start = m.start()
        line_start = raw.rfind("\n", 0, start) + 1
        indent_len = start - line_start
        if indent_len + len(collapsed) <= print_width:
            return collapsed
        return m.group(0)

    # Collapse arrays that contain only quoted strings (no nested objects/arrays)
    return re.sub(
        r'\[\n\s+("(?:[^"\\]|\\.)*"(?:,\n\s+"(?:[^"\\]|\\.)*")*)\n\s+\]',
        collapse_if_fits,
        raw,
    )

REQUIRED_FIELDS = {"event", "matcher", "surface", "signal", "role"}
VALID_SURFACES = {"user_global", "per_call_inspector", "both"}
VALID_SIGNALS = {"AGENT_TYPE", "CLAUDE_ROLE", "CLAUDE_ROLE_FAMILY", "none"}
VALID_HARNESSES = {"claude_code", "pi"}

# Generic tool names — matchers consisting only of these tokens ship to every stack.
GENERIC_TOOL_NAMES = {
    "Agent",
    "Bash",
    "Edit",
    "Glob",
    "Grep",
    "Monitor",
    "MultiEdit",
    "NotebookEdit",
    "Read",
    "Write",
}

# Hook events managed entirely by manifests — regenerated from script headers.
MANIFEST_DRIVEN_EVENTS = {"PreToolUse", "SubagentStop", "Stop", "PostToolUseFailure"}

# Hook events with inline commands — preserved verbatim from existing settings.json.
PRESERVED_EVENTS = {"PostToolUse", "UserPromptSubmit", "SessionStart", "SessionEnd"}

# Canonical event ordering in output settings.json.
EVENT_ORDER = [
    "PostToolUse",
    "PostToolUseFailure",
    "UserPromptSubmit",
    "SessionStart",
    "SessionEnd",
    "Stop",
    "SubagentStop",
    "PreToolUse",
]


def parse_manifest(script_path: Path) -> dict:
    """Parse HOOK-MANIFEST header block from a .sh file.

    Returns dict with keys: event, matcher, surface, signal, role, filename.
    Exits non-zero if required fields are missing or malformed.
    """
    content = script_path.read_text()
    lines = content.splitlines()

    in_manifest = False
    fields: dict = {}
    for line in lines:
        stripped = line.strip()
        if stripped == "# HOOK-MANIFEST:":
            in_manifest = True
            continue
        if in_manifest:
            m = re.match(r"^#\s+(\w+):\s+(.+)$", stripped)
            if m:
                key = m.group(1)
                val = m.group(2).strip()
                if key in REQUIRED_FIELDS:
                    fields[key] = val
                elif key == "harnesses":
                    fields["harnesses"] = val
                # Continue scanning for optional fields (harnesses may follow required).
            elif stripped == "#" or stripped == "":
                # Blank comment line or empty line → end of manifest key-value block.
                # Stop here to avoid parsing prose comment lines that may accidentally
                # match the key: value regex and overwrite already-parsed fields.
                break
            elif not stripped.startswith("#"):
                # Non-comment line → manifest block ended
                break

    missing = REQUIRED_FIELDS - set(fields.keys())
    if missing:
        print(
            f"ERROR: {script_path.name} is missing HOOK-MANIFEST fields: {sorted(missing)}",
            file=sys.stderr,
        )
        sys.exit(1)

    if fields["surface"] not in VALID_SURFACES:
        print(
            f"ERROR: {script_path.name} has invalid surface '{fields['surface']}'. Must be one of: {VALID_SURFACES}",
            file=sys.stderr,
        )
        sys.exit(1)

    if fields["signal"] not in VALID_SIGNALS:
        print(
            f"ERROR: {script_path.name} has invalid signal '{fields['signal']}'. Must be one of: {VALID_SIGNALS}",
            file=sys.stderr,
        )
        sys.exit(1)

    # Parse and validate optional harnesses field.
    # "all" or absent → None (ships everywhere, default).
    # Explicit list (e.g. "claude_code") → list of tokens.
    if "harnesses" in fields:
        raw_val = fields["harnesses"]
        if raw_val.strip() == "all":
            fields["harnesses"] = None  # "all" is shorthand for ships-everywhere
        else:
            tokens = [t.strip() for t in raw_val.split(",")]
            invalid = [t for t in tokens if t not in VALID_HARNESSES]
            if invalid:
                print(
                    f"ERROR: {script_path.name} has invalid harnesses tokens: {invalid}. Must be from: {VALID_HARNESSES} or 'all'",
                    file=sys.stderr,
                )
                sys.exit(1)
            fields["harnesses"] = tokens
    else:
        fields["harnesses"] = None  # None = ships everywhere (default)

    fields["filename"] = script_path.name
    return fields


def validate_role_match(script_path: Path, manifest: dict) -> None:
    """Verify that literal role values appear in script body as guard patterns.

    For literal role values (no *, |, not in {*, all}):
      - body must contain [ "$AGENT_TYPE" = "<literal>" ]
        OR case "$AGENT_TYPE" in ... <literal>) ;;
    For glob roles (planner-*, developer-*):
      - body must contain case "$AGENT_TYPE" in <glob>) ;;
        OR printf '%s' "$AGENT_TYPE" | grep -qE '^<prefix>-'
    For wildcard roles (*, all):
      - no check required.
    Exits non-zero on mismatch (prints script name + pattern detail).
    """
    signal = manifest["signal"]
    # Only validate AGENT_TYPE signal hooks — others use CLAUDE_ROLE etc.
    if signal != "AGENT_TYPE":
        return

    content = script_path.read_text()
    role_raw = manifest["role"]

    # Split multi-value roles on |
    role_tokens = [t.strip() for t in role_raw.split("|")]

    for token in role_tokens:
        # Universal wildcards — no body check needed
        if token in ("*", "all"):
            continue

        # Glob role (ends with -*)
        if token.endswith("-*"):
            prefix = token[:-2]  # strip trailing -*
            # Accept: case ... in <prefix>-*) or grep -qE '^<prefix>-'
            glob_case = f"case \"$AGENT_TYPE\" in"
            glob_pattern = f"{prefix}-"
            if glob_case not in content or glob_pattern not in content:
                # Also accept grep-based guard
                grep_pattern = f"'^{prefix}-'"
                if grep_pattern not in content and glob_pattern not in content:
                    print(
                        f"ERROR: {script_path.name} declares role: {token} (glob) but body "
                        f"does not contain case \"$AGENT_TYPE\" in ... {prefix}-*) or grep '^{prefix}-'",
                        file=sys.stderr,
                    )
                    sys.exit(1)
            continue

        # Literal role with | — multi-case, expect case statement or helper fn
        if "|" in role_raw:
            # Each token in a multi-value role must appear in a case statement,
            # OR the hook uses require_inspector_agent_type (covers all inspector roles).
            # Case patterns can be: token) OR token | othertoken)
            inspector_fn = "require_inspector_agent_type"
            token_in_case = f'{token})' in content or f'{token} |' in content or f'{token} )' in content
            if (
                f'"{token}"' not in content
                and not token_in_case
                and not ("inspector" in token and inspector_fn in content)
            ):
                print(
                    f"ERROR: {script_path.name} declares role: {token} but body "
                    f"does not contain \"{token}\" or {token}) in a case statement",
                    file=sys.stderr,
                )
                sys.exit(1)
            continue

        # Single literal role — accept [ "$AGENT_TYPE" = "<literal>" ] (equality),
        # [ "$AGENT_TYPE" != "<literal>" ] (inequality guard), case statement,
        # or require_inspector_agent_type (for inspector roles)
        eq_check = f'[ "$AGENT_TYPE" = "{token}" ]'
        ne_check = f'[ "$AGENT_TYPE" != "{token}" ]'
        case_check = f'{token})'
        inspector_fn = "require_inspector_agent_type"
        if (
            eq_check not in content
            and ne_check not in content
            and case_check not in content
            and not ("inspector" in token and inspector_fn in content)
        ):
            print(
                f"ERROR: {script_path.name} declares role: {token} but body "
                f"does not contain [ \"$AGENT_TYPE\" = \"{token}\" ] or {token}) in a case statement",
                file=sys.stderr,
            )
            sys.exit(1)


def validate_signal(script_path: Path, manifest: dict) -> None:
    """Verify declared signal appears in script body.

    Exits non-zero if signal declared but not referenced in body.

    Signal semantics:
      CLAUDE_ROLE         — body must reference CLAUDE_ROLE literal.
      CLAUDE_ROLE_FAMILY  — body must call resolve_role() (from _role.sh); supports CLAUDE_ROLE,
                            PI_ROLE with unified precedence.
      AGENT_TYPE          — body must reference AGENT_TYPE or require_inspector_agent_type.
      none                — no signal check.
    """
    signal = manifest["signal"]
    if signal == "none":
        return

    content = script_path.read_text()
    if signal == "AGENT_TYPE":
        if "AGENT_TYPE" not in content and "require_inspector_agent_type" not in content:
            print(
                f"ERROR: {script_path.name} declares signal: AGENT_TYPE but body does not reference AGENT_TYPE or require_inspector_agent_type",
                file=sys.stderr,
            )
            sys.exit(1)
    elif signal == "CLAUDE_ROLE":
        if "CLAUDE_ROLE" not in content:
            print(
                f"ERROR: {script_path.name} declares signal: CLAUDE_ROLE but body does not reference CLAUDE_ROLE",
                file=sys.stderr,
            )
            sys.exit(1)
    elif signal == "CLAUDE_ROLE_FAMILY":
        if "resolve_role" not in content:
            print(
                f"ERROR: {script_path.name} declares signal: CLAUDE_ROLE_FAMILY but body does not call resolve_role (sourced from _role.sh)",
                file=sys.stderr,
            )
            sys.exit(1)
def collect_hooks(hooks_dir: Path) -> list:  # type: ignore[type-arg]
    """Find all .sh files (excluding _test.sh, run-tests.sh, and _*.sh helpers) and parse manifests.

    Files starting with '_' are library helpers sourced by hook scripts, not registered hooks.
    Canonical example: _role.sh (shared resolve_role() helper).
    """
    hooks = []
    for sh_file in sorted(hooks_dir.glob("*.sh")):
        if sh_file.name.endswith("_test.sh"):
            continue
        if sh_file.name == "run-tests.sh":
            continue
        # Skip library helpers: files whose basename starts with '_'.
        # These are sourced by hook scripts and must not appear in settings.json.
        if sh_file.name.startswith("_"):
            continue
        manifest = parse_manifest(sh_file)
        validate_signal(sh_file, manifest)
        validate_role_match(sh_file, manifest)
        hooks.append(manifest)
    return hooks


def parse_subagent_frontmatter(subagent_path: Path) -> dict:
    """Parse YAML frontmatter between `---` lines inside `{% if tool.yaml_frontmatter %}` block.

    Returns dict with at least `name` key. Exits non-zero if `name` not found.
    """
    content = subagent_path.read_text()
    lines = content.splitlines()

    in_block = False
    in_frontmatter = False
    frontmatter_lines = []

    for line in lines:
        stripped = line.strip()
        if not in_block and "{% if tool.yaml_frontmatter %}" in stripped:
            in_block = True
            continue
        if in_block and not in_frontmatter and stripped == "---":
            in_frontmatter = True
            continue
        if in_frontmatter:
            if stripped == "---":
                break
            frontmatter_lines.append(line)

    result: dict = {}
    for fl in frontmatter_lines:
        m = re.match(r"^(\w[\w-]*):\s*(.+)$", fl.strip())
        if m:
            result[m.group(1)] = m.group(2).strip()

    if "name" not in result:
        print(
            f"ERROR: {subagent_path.name} has no `name:` in YAML frontmatter",
            file=sys.stderr,
        )
        sys.exit(1)

    return result


def collect_agents(subagents_dir: Path) -> dict:
    """Scan subagent .md.j2 templates; return stack → sorted agent-name list.

    Discovers:
    - <subagents_dir>/phoenix/*.md.j2  → "phoenix" stack
    - <subagents_dir>/static/*.md.j2   → individual static stacks (html/hugo/vite) derived from `name:` field
    - <subagents_dir>/shared/committer.md.j2 → merged into every concrete stack

    Skip files whose basename starts with '_' (shared partials).

    static_unknown = sorted union of all static stacks.
    committer is merged into every concrete stack and static_unknown.
    """
    stack_map: dict = {"phoenix": [], "static_html": [], "static_hugo": [], "static_vite": []}

    # Parse committer and curator from shared/
    shared_dir = subagents_dir / "shared"
    committer_name = None
    if (shared_dir / "committer.md.j2").exists():
        fm = parse_subagent_frontmatter(shared_dir / "committer.md.j2")
        committer_name = fm["name"]

    curator_name = None
    if (shared_dir / "context-curator.md.j2").exists():
        fm = parse_subagent_frontmatter(shared_dir / "context-curator.md.j2")
        curator_name = fm["name"]

    # Parse phoenix agents
    phoenix_dir = subagents_dir / "phoenix"
    if phoenix_dir.is_dir():
        for f in sorted(phoenix_dir.glob("*.md.j2")):
            if f.name.startswith("_"):
                continue
            fm = parse_subagent_frontmatter(f)
            stack_map["phoenix"].append(fm["name"])

    # Parse static agents — assign to stack by name prefix
    static_dir = subagents_dir / "static"
    if static_dir.is_dir():
        for f in sorted(static_dir.glob("*.md.j2")):
            if f.name.startswith("_"):
                continue
            fm = parse_subagent_frontmatter(f)
            name = fm["name"]
            if "-html" in name or name.endswith("-html"):
                stack_map["static_html"].append(name)
            elif "-hugo" in name or name.endswith("-hugo"):
                stack_map["static_hugo"].append(name)
            elif "-vite" in name or name.endswith("-vite"):
                stack_map["static_vite"].append(name)
            else:
                # reviewer-static and similar shared-across-static names go into all three
                stack_map["static_html"].append(name)
                stack_map["static_hugo"].append(name)
                stack_map["static_vite"].append(name)

    # Merge committer and curator into every concrete stack
    if committer_name:
        for key in stack_map:
            stack_map[key].append(committer_name)

    if curator_name:
        for key in stack_map:
            stack_map[key].append(curator_name)

    # Sort each stack
    for key in stack_map:
        stack_map[key] = sorted(stack_map[key])

    # static_unknown = sorted union of all static stacks
    static_union = sorted(
        set(stack_map["static_html"]) | set(stack_map["static_hugo"]) | set(stack_map["static_vite"])
    )
    stack_map["static_unknown"] = static_union

    return stack_map


def write_agent_manifest(agents: dict, combobulate_dir: Path) -> None:
    """Write priv/claude_config/agent_manifest.json."""
    claude_priv_dir = combobulate_dir / "priv" / "claude_config"
    claude_priv_dir.mkdir(parents=True, exist_ok=True)
    manifest_path = claude_priv_dir / "agent_manifest.json"
    manifest_path.write_text(json.dumps(agents, indent=2) + "\n")
    print(f"Wrote {manifest_path}")


def _hook_fits_stack(hook: dict, agent_set: list) -> bool:
    """Return True if hook is applicable to a stack with the given agent_set.

    Stack-fit heuristic (Approach 3):
      (a) All matcher tokens are generic tool names (ships everywhere), OR
      (b) Any matcher token (split on |) intersects the agent set, OR
      (c) Any role token (split on |, ignoring *, all, developer-*) intersects the agent set, OR
      (d) Role is one of the universal wildcards: *, all, or developer-*
    """
    agent_set_s = set(agent_set)
    matcher_tokens = [t.strip() for t in hook["matcher"].split("|")]
    role_tokens = [t.strip() for t in hook["role"].split("|")]

    # (a) All matcher tokens are generic tool names
    if all(t in GENERIC_TOOL_NAMES for t in matcher_tokens):
        return True

    # (b) Matcher tokens intersect agent set
    if agent_set_s & set(matcher_tokens):
        return True

    # (c/d) Role token analysis
    for token in role_tokens:
        if token in ("*", "all"):
            return True
        if token.endswith("-*") or token == "developer-*":
            return True
        if token in agent_set_s:
            return True

    return False


def write_stack_fit_reference(hooks: list, agents: dict, hooks_md_path: Path) -> None:
    """Write ## Stack-Fit Reference table between <!-- BEGIN GENERATED --> / <!-- END GENERATED --> markers.

    If markers absent, appends a new prose section + markers at file end.
    Idempotent: re-running produces identical content.
    """
    BEGIN_MARKER = "<!-- BEGIN GENERATED -->"
    END_MARKER = "<!-- END GENERATED -->"

    stack_keys = ["phoenix", "static_html", "static_hugo", "static_vite", "static_unknown"]

    # Build table rows — one per hook, sorted alphabetically by filename
    rows = []
    for hook in sorted(hooks, key=lambda x: x["filename"]):
        applicable_stacks = [k for k in stack_keys if _hook_fits_stack(hook, agents.get(k, []))]
        stacks_str = ", ".join(applicable_stacks) if applicable_stacks else "—"
        harnesses = hook.get("harnesses")
        if harnesses is None:
            harnesses_str = "all"
        else:
            harnesses_str = ", ".join(harnesses)
        # Replace | with \| in matcher so Prettier doesn't split the cell into columns.
        matcher_escaped = hook["matcher"].replace("|", "\\|")
        rows.append(
            f"| `{hook['filename']}` | {hook['event']} | `{matcher_escaped}` | {stacks_str} | {harnesses_str} |"
        )

    table_lines = [
        "<!-- prettier-ignore -->",
        "| hook | event | matcher | stacks | harnesses |",
        "| ---- | ----- | ------- | ------ | --------- |",
    ] + rows

    generated_block = "\n".join(table_lines)

    content = hooks_md_path.read_text()

    if BEGIN_MARKER in content and END_MARKER in content:
        # Replace existing block between markers
        before = content[: content.index(BEGIN_MARKER) + len(BEGIN_MARKER)].rstrip()
        after = content[content.index(END_MARKER):].lstrip()
        new_content = before + "\n\n" + generated_block + "\n\n" + after
    else:
        # Append prose section + markers + table at end
        prose = (
            "\n\n## Stack-Fit Reference\n\n"
            "Auto-generated by `make install` from `hook_manifest.json` + `agent_manifest.json`.\n"
            "Shows which stacks each hook applies to, derived by the stack-fit heuristic in\n"
            "`templates/generator/hook_registrations.py`. Do not hand-edit — re-run `make install`.\n\n"
        )
        new_content = content + prose + BEGIN_MARKER + "\n\n" + generated_block + "\n\n" + END_MARKER + "\n"

    hooks_md_path.write_text(new_content)
    print(f"Wrote stack-fit reference → {hooks_md_path}")


def build_hook_entry(manifest: dict) -> dict:
    """Build a Claude Code settings.json hook entry."""
    return {
        "type": "command",
        "command": f"$HOME/.claude/hooks/{manifest['filename']}",
    }


def load_existing_settings(settings_path: Path, existing_settings_path=None) -> dict:
    """Load existing settings.json for preserved-event extraction.

    If --existing-settings is provided, read from there (used by hook-parity to
    supply the committed file as the source of preserved events while writing output
    to /tmp). Otherwise, read from settings_path itself.
    """
    source = existing_settings_path if existing_settings_path is not None else settings_path
    if source.exists():
        return json.loads(source.read_text())
    return {}


def group_by_event(hooks: list) -> dict:
    """Group hooks by event type, sorted alphabetically by filename within each event."""
    groups: dict = {}
    for h in sorted(hooks, key=lambda x: x["filename"]):
        event = h["event"]
        groups.setdefault(event, [])
        groups[event].append(h)
    return groups


def regenerate_settings(
    existing: dict, user_global_hooks: list, settings_path: Path
) -> None:
    """Regenerate the hooks section of settings.json with user_global hooks.

    Preserves all top-level non-hooks keys verbatim.
    Preserves PRESERVED_EVENTS hook entries verbatim.
    Rebuilds MANIFEST_DRIVEN_EVENTS from user_global_hooks.
    """
    # Start with a copy of everything except hooks
    settings = {k: v for k, v in existing.items() if k != "hooks"}

    existing_hooks = existing.get("hooks", {})
    new_hooks: dict = {}

    # Preserve non-manifest-driven events verbatim
    for evt in PRESERVED_EVENTS:
        if evt in existing_hooks:
            new_hooks[evt] = existing_hooks[evt]

    # Build manifest-driven events from user_global hooks
    by_event = group_by_event(user_global_hooks)

    for evt in MANIFEST_DRIVEN_EVENTS:
        if evt not in by_event:
            continue
        entries = []
        for h in by_event[evt]:
            hook_cmd = build_hook_entry(h)
            matcher = h["matcher"]

            if evt == "Stop" and matcher == "*":
                # Stop hooks with wildcard matcher: no matcher key
                entries.append({"hooks": [hook_cmd]})
            elif evt == "SubagentStop":
                entries.append({"matcher": matcher, "hooks": [hook_cmd]})
            elif evt == "PostToolUseFailure":
                entries.append({"matcher": matcher, "hooks": [hook_cmd]})
            else:
                entries.append({"matcher": matcher, "hooks": [hook_cmd]})
        new_hooks[evt] = entries

    # Assemble in canonical order
    ordered_hooks: dict = {}
    for evt in EVENT_ORDER:
        if evt in new_hooks:
            ordered_hooks[evt] = new_hooks[evt]
    # Append any remaining events not in EVENT_ORDER
    for evt in new_hooks:
        if evt not in ordered_hooks:
            ordered_hooks[evt] = new_hooks[evt]

    settings["hooks"] = ordered_hooks
    settings_path.write_text(dumps_compact(settings) + "\n")
    print(f"Wrote {settings_path}")


def validate_pi_ts_handlers(pi_hooks: list, pi_extension_dir: Path) -> None:
    """Verify every Pi-targeted hook has a matching TypeScript handler.

    For each hook in pi_hooks, derives handler name = filename without .sh extension,
    then checks <pi_extension_dir>/src/hooks/<name>.ts exists.
    Exits non-zero with a descriptive message listing all missing handlers.
    """
    hooks_src_dir = pi_extension_dir / "src" / "hooks"
    missing = []
    for h in sorted(pi_hooks, key=lambda x: x["filename"]):
        name = h["filename"][:-3] if h["filename"].endswith(".sh") else h["filename"]
        ts_path = hooks_src_dir / f"{name}.ts"
        if not ts_path.exists():
            missing.append(f"  {h['filename']} → expected {ts_path}")

    if missing:
        print(
            "ERROR: Pi handler parity check FAILED. "
            f"The following {len(missing)} hook(s) have no TypeScript handler in "
            f"{hooks_src_dir}:\n" + "\n".join(missing) + "\n"
            "Add the missing .ts handler(s) before running make install.",
            file=sys.stderr,
        )
        sys.exit(1)

    print(f"Pi TS handler parity: OK ({len(pi_hooks)} hooks matched)")


def write_combobulate_artifacts(
    per_call_hooks: list, all_hooks: list, combobulate_dir: Path,
    pi_extension_dir: "Path | None" = None,
) -> None:
    """Write inspector_settings.json and hook_manifest.json into combobulate/priv/<harness>_config/.

    priv/claude_config/ — canonical full manifest (all hooks) + claude-prefixed inspector entries.
    priv/pi_config/     — pi-prefixed inspector entries (empty today).

    The full hook_manifest.json in claude_config is kept for backward compat with
    check_user_global_parity!/1 which loads all registered hooks.
    """
    # ── claude_config (canonical) ────────────────────────────────────────────
    claude_priv_dir = combobulate_dir / "priv" / "claude_config"
    claude_priv_dir.mkdir(parents=True, exist_ok=True)

    # inspector_settings.json: claude-prefixed per_call_inspector entries only
    claude_inspector_hooks = [h for h in per_call_hooks if h["filename"].startswith("claude-")]
    claude_inspector_entries = []
    for h in sorted(claude_inspector_hooks, key=lambda x: x["filename"]):
        claude_inspector_entries.append(
            {
                "event": h["event"],
                "matcher": h["matcher"],
                "hookScript": h["filename"],
                "surface": h["surface"],
                "signal": h["signal"],
                "role": h["role"],
            }
        )
    claude_inspector_path = claude_priv_dir / "inspector_settings.json"
    claude_inspector_path.write_text(json.dumps(claude_inspector_entries, indent=2) + "\n")
    print(f"Wrote {claude_inspector_path}")

    # hook_manifest.json: full canonical list of ALL hooks (used by check_user_global_parity!/1)
    manifest_entries = []
    for h in sorted(all_hooks, key=lambda x: x["filename"]):
        entry = {
            "filename": h["filename"],
            "event": h["event"],
            "matcher": h["matcher"],
            "surface": h["surface"],
            "signal": h["signal"],
            "role": h["role"],
            "harnesses": h.get("harnesses"),  # None = ships everywhere; list = explicit opt-in
        }
        manifest_entries.append(entry)
    manifest_path = claude_priv_dir / "hook_manifest.json"
    manifest_path.write_text(json.dumps(manifest_entries, indent=2) + "\n")
    print(f"Wrote {manifest_path}")
    claude_hash_path = claude_priv_dir / "expected_hook_manifest_hash.txt"
    claude_hash_path.write_text(hashlib.md5(manifest_path.read_bytes()).hexdigest())
    print(f"Wrote {claude_hash_path}")

    # ── pi_config ─────────────────────────────────────────────────────────────
    # Pi uses load-gate (no per-call hooks), so the manifest is always empty.
    # Only hooks that explicitly declare harnesses: pi are included; today none do.
    pi_priv_dir = combobulate_dir / "priv" / "pi_config"
    pi_priv_dir.mkdir(parents=True, exist_ok=True)

    pi_hooks = [
        h for h in all_hooks
        if "pi" in (h.get("harnesses") or [])
    ]

    pi_inspector_path = pi_priv_dir / "inspector_settings.json"
    pi_inspector_path.write_text(json.dumps([], indent=2) + "\n")
    print(f"Wrote {pi_inspector_path}")

    pi_manifest_entries = []
    for h in sorted(pi_hooks, key=lambda x: x["filename"]):
        pi_manifest_entries.append(
            {
                "filename": h["filename"],
                "event": h["event"],
                "matcher": h["matcher"],
                "surface": h["surface"],
                "signal": h["signal"],
                "role": h["role"],
            }
        )
    pi_manifest_path = pi_priv_dir / "hook_manifest.json"
    pi_manifest_path.write_text(json.dumps(pi_manifest_entries, indent=2) + "\n")
    print(f"Wrote {pi_manifest_path} ({len(pi_manifest_entries)} Pi-targeted hooks)")
    pi_hash_path = pi_priv_dir / "expected_hook_manifest_hash.txt"
    pi_hash_path.write_text(hashlib.md5(pi_manifest_path.read_bytes()).hexdigest())
    print(f"Wrote {pi_hash_path}")

    # Validate TS handler parity if pi-extension-dir provided
    if pi_extension_dir is not None:
        validate_pi_ts_handlers(pi_hooks, pi_extension_dir)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate hook registration JSONs from HOOK-MANIFEST headers"
    )
    parser.add_argument(
        "--hooks-dir", required=True, help="Directory containing .sh hook files"
    )
    parser.add_argument(
        "--output-settings",
        required=True,
        help="Path to write regenerated claude-code-settings.json",
    )
    parser.add_argument(
        "--existing-settings",
        help="Path to read existing settings from (for preserved events). Defaults to --output-settings.",
    )
    parser.add_argument(
        "--combobulate-dir",
        help="Path to combobulate repo (writes priv/claude_config/ artifacts)",
    )
    parser.add_argument(
        "--subagents-dir",
        help="Path to subagents template directory (writes priv/claude_config/agent_manifest.json)",
    )
    parser.add_argument(
        "--hooks-md-path",
        help="Path to context/hooks.md (updates Stack-Fit Reference section)",
    )
    parser.add_argument(
        "--pi-extension-dir",
        help="Path to Pi extension package root (validates TS handler parity for Pi-targeted hooks)",
    )
    args = parser.parse_args()

    hooks_dir = Path(args.hooks_dir)
    if not hooks_dir.is_dir():
        print(f"ERROR: --hooks-dir '{hooks_dir}' is not a directory", file=sys.stderr)
        sys.exit(1)

    settings_path = Path(args.output_settings)
    existing_settings_path = Path(args.existing_settings) if args.existing_settings else None

    # Collect and parse all hooks
    all_hooks = collect_hooks(hooks_dir)

    # Partition by surface
    user_global_hooks = [h for h in all_hooks if h["surface"] in ("user_global", "both")]
    per_call_hooks = [h for h in all_hooks if h["surface"] in ("per_call_inspector", "both")]

    print(
        f"Found {len(all_hooks)} hooks: {len(user_global_hooks)} user_global, {len(per_call_hooks)} per_call_inspector"
    )

    # Regenerate settings.json
    existing = load_existing_settings(settings_path, existing_settings_path)
    regenerate_settings(existing, user_global_hooks, settings_path)

    # Write combobulate artifacts if requested
    agents: dict = {}
    if args.combobulate_dir:
        combobulate_dir = Path(args.combobulate_dir)
        pi_ext_dir = Path(args.pi_extension_dir) if args.pi_extension_dir else None
        write_combobulate_artifacts(per_call_hooks, all_hooks, combobulate_dir, pi_ext_dir)

        if args.subagents_dir:
            subagents_dir = Path(args.subagents_dir)
            if not subagents_dir.is_dir():
                print(
                    f"ERROR: --subagents-dir '{subagents_dir}' is not a directory",
                    file=sys.stderr,
                )
                sys.exit(1)
            agents = collect_agents(subagents_dir)
            write_agent_manifest(agents, combobulate_dir)

    if agents and args.hooks_md_path:
        hooks_md_path = Path(args.hooks_md_path)
        if not hooks_md_path.exists():
            print(
                f"ERROR: --hooks-md-path '{hooks_md_path}' does not exist",
                file=sys.stderr,
            )
            sys.exit(1)
        write_stack_fit_reference(all_hooks, agents, hooks_md_path)

    print("hook_registrations.py: OK")


if __name__ == "__main__":
    main()
