#!/usr/bin/env python3
"""hook_registrations.py — Parse HOOK-MANIFEST headers and generate hook registration JSONs.

Usage:
    python3 templates/generator/hook_registrations.py \
        --hooks-dir templates/shared/hooks \
        --output-settings templates/claude-code-settings.json \
        --combobulate-dir /path/to/combobulate

Algorithm:
    1. Find all .sh files (excluding _test.sh and run-tests.sh) in --hooks-dir.
    2. Parse HOOK-MANIFEST header block (event, matcher, surface, signal, role).
    3. Validate declared signal appears in script body.
    4. Build user_global and per_call_inspector lists.
    5. Emit --output-settings (user_global entries replace manifest-driven hook events;
       non-manifest-driven events preserved verbatim from existing JSON).
    6. Emit priv/claude_config/inspector_settings.json and hook_manifest.json
       (if --combobulate-dir provided).

Non-manifest-driven hook events (preserved verbatim from existing settings.json):
    PostToolUse, UserPromptSubmit, SessionStart, SessionEnd

These contain inline bash commands that cannot be expressed as hook scripts,
so they are never regenerated by this tool.

Manifest-driven hook events (fully regenerated):
    PreToolUse, SubagentStop, Stop, PostToolUseFailure

Hook ordering within each event:
    Sorted alphabetically by filename for deterministic output.
"""

import argparse
import json
import os
import re
import sys
from pathlib import Path

REQUIRED_FIELDS = {"event", "matcher", "surface", "signal", "role"}
VALID_SURFACES = {"user_global", "per_call_inspector", "both"}
VALID_SIGNALS = {"AGENT_TYPE", "CLAUDE_ROLE", "CLAUDE_ROLE_FAMILY", "CODEX_ROLE", "none"}

# Hook events managed entirely by manifests — regenerated from script headers.
MANIFEST_DRIVEN_EVENTS = {"PreToolUse", "SubagentStop", "Stop", "PostToolUseFailure"}

# Hook events with inline commands — preserved verbatim from existing settings.json.
PRESERVED_EVENTS = {"PostToolUse", "UserPromptSubmit", "SessionStart", "SessionEnd"}

# Canonical event ordering in output settings.json.
EVENT_ORDER = [
    "PostToolUse",
    "PostToolUseFailure",
    "UserPromptSubmit",
    "SessionStart",
    "SessionEnd",
    "Stop",
    "SubagentStop",
    "PreToolUse",
]


def parse_manifest(script_path: Path) -> dict:
    """Parse HOOK-MANIFEST header block from a .sh file.

    Returns dict with keys: event, matcher, surface, signal, role, filename.
    Exits non-zero if required fields are missing or malformed.
    """
    content = script_path.read_text()
    lines = content.splitlines()

    in_manifest = False
    fields: dict = {}
    for line in lines:
        stripped = line.strip()
        if stripped == "# HOOK-MANIFEST:":
            in_manifest = True
            continue
        if in_manifest:
            m = re.match(r"^#\s+(\w+):\s+(.+)$", stripped)
            if m:
                key = m.group(1)
                val = m.group(2).strip()
                if key in REQUIRED_FIELDS:
                    fields[key] = val
            elif stripped.startswith("#") or stripped == "":
                # Still in comment block — continue
                continue
            else:
                # Non-comment line after manifest start — manifest block ended
                break

    missing = REQUIRED_FIELDS - set(fields.keys())
    if missing:
        print(
            f"ERROR: {script_path.name} is missing HOOK-MANIFEST fields: {sorted(missing)}",
            file=sys.stderr,
        )
        sys.exit(1)

    if fields["surface"] not in VALID_SURFACES:
        print(
            f"ERROR: {script_path.name} has invalid surface '{fields['surface']}'. Must be one of: {VALID_SURFACES}",
            file=sys.stderr,
        )
        sys.exit(1)

    if fields["signal"] not in VALID_SIGNALS:
        print(
            f"ERROR: {script_path.name} has invalid signal '{fields['signal']}'. Must be one of: {VALID_SIGNALS}",
            file=sys.stderr,
        )
        sys.exit(1)

    fields["filename"] = script_path.name
    return fields


def validate_signal(script_path: Path, manifest: dict) -> None:
    """Verify declared signal appears in script body.

    Exits non-zero if signal declared but not referenced in body.

    Signal semantics:
      CLAUDE_ROLE         — body must reference CLAUDE_ROLE literal.
      CLAUDE_ROLE_FAMILY  — body must call resolve_role() (from _role.sh); supports CLAUDE_ROLE,
                            PI_ROLE, CODEX_ROLE with unified precedence.
      CODEX_ROLE          — body must reference CODEX_ROLE literal.
      AGENT_TYPE          — body must reference AGENT_TYPE or require_inspector_agent_type.
      none                — no signal check.
    """
    signal = manifest["signal"]
    if signal == "none":
        return

    content = script_path.read_text()
    if signal == "AGENT_TYPE":
        if "AGENT_TYPE" not in content and "require_inspector_agent_type" not in content:
            print(
                f"ERROR: {script_path.name} declares signal: AGENT_TYPE but body does not reference AGENT_TYPE or require_inspector_agent_type",
                file=sys.stderr,
            )
            sys.exit(1)
    elif signal == "CLAUDE_ROLE":
        if "CLAUDE_ROLE" not in content:
            print(
                f"ERROR: {script_path.name} declares signal: CLAUDE_ROLE but body does not reference CLAUDE_ROLE",
                file=sys.stderr,
            )
            sys.exit(1)
    elif signal == "CLAUDE_ROLE_FAMILY":
        if "resolve_role" not in content:
            print(
                f"ERROR: {script_path.name} declares signal: CLAUDE_ROLE_FAMILY but body does not call resolve_role (sourced from _role.sh)",
                file=sys.stderr,
            )
            sys.exit(1)
    elif signal == "CODEX_ROLE":
        if "CODEX_ROLE" not in content:
            print(
                f"ERROR: {script_path.name} declares signal: CODEX_ROLE but body does not reference CODEX_ROLE",
                file=sys.stderr,
            )
            sys.exit(1)


def collect_hooks(hooks_dir: Path) -> list:  # type: ignore[type-arg]
    """Find all .sh files (excluding _test.sh, run-tests.sh, and _*.sh helpers) and parse manifests.

    Files starting with '_' are library helpers sourced by hook scripts, not registered hooks.
    Canonical example: _role.sh (shared resolve_role() helper).
    """
    hooks = []
    for sh_file in sorted(hooks_dir.glob("*.sh")):
        if sh_file.name.endswith("_test.sh"):
            continue
        if sh_file.name == "run-tests.sh":
            continue
        # Skip library helpers: files whose basename starts with '_'.
        # These are sourced by hook scripts and must not appear in settings.json.
        if sh_file.name.startswith("_"):
            continue
        manifest = parse_manifest(sh_file)
        validate_signal(sh_file, manifest)
        hooks.append(manifest)
    return hooks


def build_hook_entry(manifest: dict) -> dict:
    """Build a Claude Code settings.json hook entry."""
    return {
        "type": "command",
        "command": f"$HOME/.claude/hooks/{manifest['filename']}",
    }


def load_existing_settings(settings_path: Path, existing_settings_path=None) -> dict:
    """Load existing settings.json for preserved-event extraction.

    If --existing-settings is provided, read from there (used by hook-parity to
    supply the committed file as the source of preserved events while writing output
    to /tmp). Otherwise, read from settings_path itself.
    """
    source = existing_settings_path if existing_settings_path is not None else settings_path
    if source.exists():
        return json.loads(source.read_text())
    return {}


def group_by_event(hooks: list) -> dict:
    """Group hooks by event type, sorted alphabetically by filename within each event."""
    groups: dict = {}
    for h in sorted(hooks, key=lambda x: x["filename"]):
        event = h["event"]
        groups.setdefault(event, [])
        groups[event].append(h)
    return groups


def regenerate_settings(
    existing: dict, user_global_hooks: list, settings_path: Path
) -> None:
    """Regenerate the hooks section of settings.json with user_global hooks.

    Preserves all top-level non-hooks keys verbatim.
    Preserves PRESERVED_EVENTS hook entries verbatim.
    Rebuilds MANIFEST_DRIVEN_EVENTS from user_global_hooks.
    """
    # Start with a copy of everything except hooks
    settings = {k: v for k, v in existing.items() if k != "hooks"}

    existing_hooks = existing.get("hooks", {})
    new_hooks: dict = {}

    # Preserve non-manifest-driven events verbatim
    for evt in PRESERVED_EVENTS:
        if evt in existing_hooks:
            new_hooks[evt] = existing_hooks[evt]

    # Build manifest-driven events from user_global hooks
    by_event = group_by_event(user_global_hooks)

    for evt in MANIFEST_DRIVEN_EVENTS:
        if evt not in by_event:
            continue
        entries = []
        for h in by_event[evt]:
            hook_cmd = build_hook_entry(h)
            matcher = h["matcher"]

            if evt == "Stop" and matcher == "*":
                # Stop hooks with wildcard matcher: no matcher key
                entries.append({"hooks": [hook_cmd]})
            elif evt == "SubagentStop":
                entries.append({"matcher": matcher, "hooks": [hook_cmd]})
            elif evt == "PostToolUseFailure":
                entries.append({"matcher": matcher, "hooks": [hook_cmd]})
            else:
                entries.append({"matcher": matcher, "hooks": [hook_cmd]})
        new_hooks[evt] = entries

    # Assemble in canonical order
    ordered_hooks: dict = {}
    for evt in EVENT_ORDER:
        if evt in new_hooks:
            ordered_hooks[evt] = new_hooks[evt]
    # Append any remaining events not in EVENT_ORDER
    for evt in new_hooks:
        if evt not in ordered_hooks:
            ordered_hooks[evt] = new_hooks[evt]

    settings["hooks"] = ordered_hooks
    settings_path.write_text(json.dumps(settings, indent=2) + "\n")
    print(f"Wrote {settings_path}")


def write_combobulate_artifacts(
    per_call_hooks: list, all_hooks: list, combobulate_dir: Path
) -> None:
    """Write inspector_settings.json and hook_manifest.json into combobulate/priv/<harness>_config/.

    priv/claude_config/ — canonical full manifest (all hooks) + claude-prefixed inspector entries.
    priv/codex_config/  — codex-prefixed inspector entries.
    priv/pi_config/     — pi-prefixed inspector entries (empty today).

    The full hook_manifest.json in claude_config is kept for backward compat with
    check_user_global_parity!/1 which loads all registered hooks.
    """
    # ── claude_config (canonical) ────────────────────────────────────────────
    claude_priv_dir = combobulate_dir / "priv" / "claude_config"
    claude_priv_dir.mkdir(parents=True, exist_ok=True)

    # inspector_settings.json: claude-prefixed per_call_inspector entries only
    claude_inspector_hooks = [h for h in per_call_hooks if h["filename"].startswith("claude-")]
    claude_inspector_entries = []
    for h in sorted(claude_inspector_hooks, key=lambda x: x["filename"]):
        claude_inspector_entries.append(
            {
                "event": h["event"],
                "matcher": h["matcher"],
                "hookScript": h["filename"],
                "surface": h["surface"],
                "signal": h["signal"],
                "role": h["role"],
            }
        )
    claude_inspector_path = claude_priv_dir / "inspector_settings.json"
    claude_inspector_path.write_text(json.dumps(claude_inspector_entries, indent=2) + "\n")
    print(f"Wrote {claude_inspector_path}")

    # hook_manifest.json: full canonical list of ALL hooks (used by check_user_global_parity!/1)
    manifest_entries = []
    for h in sorted(all_hooks, key=lambda x: x["filename"]):
        manifest_entries.append(
            {
                "filename": h["filename"],
                "event": h["event"],
                "matcher": h["matcher"],
                "surface": h["surface"],
                "signal": h["signal"],
                "role": h["role"],
            }
        )
    manifest_path = claude_priv_dir / "hook_manifest.json"
    manifest_path.write_text(json.dumps(manifest_entries, indent=2) + "\n")
    print(f"Wrote {manifest_path}")

    # ── codex_config ─────────────────────────────────────────────────────────
    codex_priv_dir = combobulate_dir / "priv" / "codex_config"
    codex_priv_dir.mkdir(parents=True, exist_ok=True)

    codex_inspector_hooks = [h for h in per_call_hooks if h["filename"].startswith("codex-")]
    codex_inspector_entries = []
    for h in sorted(codex_inspector_hooks, key=lambda x: x["filename"]):
        codex_inspector_entries.append(
            {
                "event": h["event"],
                "matcher": h["matcher"],
                "hookScript": h["filename"],
                "surface": h["surface"],
                "signal": h["signal"],
                "role": h["role"],
            }
        )
    codex_inspector_path = codex_priv_dir / "inspector_settings.json"
    codex_inspector_path.write_text(json.dumps(codex_inspector_entries, indent=2) + "\n")
    print(f"Wrote {codex_inspector_path}")

    codex_manifest_entries = []
    for h in sorted(codex_inspector_hooks, key=lambda x: x["filename"]):
        codex_manifest_entries.append(
            {
                "filename": h["filename"],
                "event": h["event"],
                "matcher": h["matcher"],
                "surface": h["surface"],
                "signal": h["signal"],
                "role": h["role"],
            }
        )
    codex_manifest_path = codex_priv_dir / "hook_manifest.json"
    codex_manifest_path.write_text(json.dumps(codex_manifest_entries, indent=2) + "\n")
    print(f"Wrote {codex_manifest_path}")

    # ── pi_config (empty today — pi uses load-gate enforcement, no per-call hooks) ──
    pi_priv_dir = combobulate_dir / "priv" / "pi_config"
    pi_priv_dir.mkdir(parents=True, exist_ok=True)

    pi_inspector_hooks = [h for h in per_call_hooks if h["filename"].startswith("pi-")]
    pi_inspector_entries = []
    for h in sorted(pi_inspector_hooks, key=lambda x: x["filename"]):
        pi_inspector_entries.append(
            {
                "event": h["event"],
                "matcher": h["matcher"],
                "hookScript": h["filename"],
                "surface": h["surface"],
                "signal": h["signal"],
                "role": h["role"],
            }
        )
    pi_inspector_path = pi_priv_dir / "inspector_settings.json"
    pi_inspector_path.write_text(json.dumps(pi_inspector_entries, indent=2) + "\n")
    print(f"Wrote {pi_inspector_path}")

    pi_manifest_entries = []
    for h in sorted(pi_inspector_hooks, key=lambda x: x["filename"]):
        pi_manifest_entries.append(
            {
                "filename": h["filename"],
                "event": h["event"],
                "matcher": h["matcher"],
                "surface": h["surface"],
                "signal": h["signal"],
                "role": h["role"],
            }
        )
    pi_manifest_path = pi_priv_dir / "hook_manifest.json"
    pi_manifest_path.write_text(json.dumps(pi_manifest_entries, indent=2) + "\n")
    print(f"Wrote {pi_manifest_path}")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate hook registration JSONs from HOOK-MANIFEST headers"
    )
    parser.add_argument(
        "--hooks-dir", required=True, help="Directory containing .sh hook files"
    )
    parser.add_argument(
        "--output-settings",
        required=True,
        help="Path to write regenerated claude-code-settings.json",
    )
    parser.add_argument(
        "--existing-settings",
        help="Path to read existing settings from (for preserved events). Defaults to --output-settings.",
    )
    parser.add_argument(
        "--combobulate-dir",
        help="Path to combobulate repo (writes priv/claude_config/ artifacts)",
    )
    args = parser.parse_args()

    hooks_dir = Path(args.hooks_dir)
    if not hooks_dir.is_dir():
        print(f"ERROR: --hooks-dir '{hooks_dir}' is not a directory", file=sys.stderr)
        sys.exit(1)

    settings_path = Path(args.output_settings)
    existing_settings_path = Path(args.existing_settings) if args.existing_settings else None

    # Collect and parse all hooks
    all_hooks = collect_hooks(hooks_dir)

    # Partition by surface
    user_global_hooks = [h for h in all_hooks if h["surface"] in ("user_global", "both")]
    per_call_hooks = [h for h in all_hooks if h["surface"] in ("per_call_inspector", "both")]

    print(
        f"Found {len(all_hooks)} hooks: {len(user_global_hooks)} user_global, {len(per_call_hooks)} per_call_inspector"
    )

    # Regenerate settings.json
    existing = load_existing_settings(settings_path, existing_settings_path)
    regenerate_settings(existing, user_global_hooks, settings_path)

    # Write combobulate artifacts if requested
    if args.combobulate_dir:
        combobulate_dir = Path(args.combobulate_dir)
        write_combobulate_artifacts(per_call_hooks, all_hooks, combobulate_dir)

    print("hook_registrations.py: OK")


if __name__ == "__main__":
    main()
